### ISSUE TITLE
How do you do monitoring?

### ISSUE THREAD

**Issue by dAnjou** [nameko/nameko#243]
Is there anything like [Flower for Celery](http://flower.readthedocs.org/), or is this not comparable? Or maybe you have a special setup of external tools?

**Comment by mattbennett** [comment]
This is a great question that we don't touch on in the docs (but should).

Short answer: 

Nameko does't dictate any particular tool. At onefinestay we log exceptions to sentry, timing stats to graphite and entrypoint invocation (service and method name, arguments, call stack, success/error status, result bytes, response time etc.) to elasticsearch/logstash. This is a really powerful setup for debugging across multiple services.

Each of these loggers are service dependencies, and we intend to open source each of them as [community extensions](http://nameko.readthedocs.org/en/latest/community_extensions.html).


Longer answer:

One of the nice things about nameko's dependency injection pattern is the integration with the worker lifecycle. DependencyProvider extensions are notified when workers are setup, torn down, and generate a result. A trivial logging dependency might look like:

``` python
class LoggingDependency(DependencyProvider):

    def __init__(self):
        self.timestamps = WeakKeyDictionary()

    def worker_setup(self, worker_ctx):
      
        self.timestamps[worker_ctx] = datetime.datetime.now()
      
        service_name = worker_ctx.service_name
        method_name = worker_ctx.entrypoint.method_name

        log.info("Worker %s.%s starting", service_name, method_name)

    def worker_result(self, worker_ctx, result=None, exc_info=None):

        service_name = worker_ctx.service_name
        method_name = worker_ctx.entrypoint.method_name

        if exc_info is None:
            status = "completed"
        else:
            status = "errored"

        now = datetime.datetime.now()
        worker_started = self.timestamps.pop(worker_ctx)
        elapsed = (now - worker_started).seconds

        log.info("Worker %s.%s %s after %ss",
                 service_name, method_name, status, elapsed)
```

Then you can add it to your service in a nicely decoupled way:

```python
class Service(object):
    name = "myservice"

    logger = LoggingDependency()  # << just add this line

    @rpc
    def method(self, arg):
        ...
```

**Comment by dAnjou** [comment]
Really nice answer, thank you very much!

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/how-do-you-do-monitoring/319
