### ISSUE TITLE
Make it more obvious the example needs rabbitmq

### ISSUE THREAD

**Issue by mattbennett** [nameko/nameko#276]
The example service on the index page encourages you to just try to run it, which fails if you haven't installed RabbitMQ. Make it more obvious you need to follow the installation process first.

This should perhaps get lumped into a larger piece of work to separate out the project page from the docs page.

**Comment by jiamo** [comment]
Just about the doc. I only find code in test uinsg py.test framework to test service. Can we have some examples don't using py.test. In real project we may don't use py.test helper as client code to call service.

**Comment by mattbennett** [comment]
Nameko uses py.test for its own tests, and we encourage others to do so as well. It's also basically compatible with the other testing frameworks, so I don't see much value in adding non-pytest examples. You should be able to port the same concepts to another testing framework if you really need to.

**Comment by omidraha** [comment]
It's obviously, but please add something like this to the example of index page:

> To run above code, insure that you have RabbitMQ running, for example:
> `$ docker run  -p5672:5672 rabbitmq:latest`

**Comment by tyler46** [comment]
@mattbennett I can handle this addition on the docs if it's ok.

**Comment by mattbennett** [comment]
@tyler46 yes please!

**Comment by tyler46** [comment]
@mattbennett great, I will prepare a PR for review.

**Comment by iky** [comment]
Fixed by https://github.com/nameko/nameko/pull/591
