### ISSUE TITLE
Cannot use custom exceptions in a http web handler

### ISSUE THREAD

**Issue by javaguirre** [nameko/nameko#284]
Hi! I would like if we could think of a better solution for this.

https://github.com/onefinestay/nameko/blob/master/nameko/web/handlers.py#L85-L86

``` python
        except Exception as exc:
            if (
                isinstance(exc, self.expected_exceptions) or
                isinstance(exc, BadRequest)
            ):
                status_code = 400
            else:
                status_code = 500
            error_dict = serialize(exc)
            payload = u'Error: {exc_type}: {value}\n'.format(**error_dict)

            response = Response(
                payload,
                status=status_code,
            )
        return response
```

Actually It's always catching all exceptions and returning a 500 error (except BadRequest), but I think the exception handling of those errors shouldn't be there, but controlled by the developer in case He/She wants to catch an expected custom exception.

Because of this design decision I also find It very difficult to debug because I can't get the traceback right away while developing, just the 500, but the full trace is expected in the log IMHO. I know the error is in the response data, but a change in the log format is needed to get the exception trace thrown right away on the command line.

Thank you for Nameko! :+1:

**Comment by javaguirre** [comment]
I think It might be related with https://github.com/onefinestay/nameko/pull/275.

**Comment by mattbennett** [comment]
Hi @javaguirre, thanks for raising this. It does relate partly to #275.

Generally we might want to think about a debug mode for the web handler that will return the stack trace when enabled (for example as flask and django do). At the very least we should make it easier to debug service errors with better default logging and/or docs on how to attach logging.

Watch this space.
