### ISSUE TITLE
nameko crashed: [Errno 111] ECONNREFUSED

### ISSUE THREAD

**Issue by genbits** [nameko/nameko#346]
Hi guys,

Just got this from our production server (we're using airbrake for catching errors):

<pre>
/usr/lib/python2.7/dist-packages/nameko/cli/main.py:26:in main
/usr/lib/python2.7/dist-packages/nameko/cli/run.py:182:in main
/usr/lib/python2.7/dist-packages/nameko/cli/run.py:132:in run
/usr/lib/python2.7/dist-packages/nameko/runners.py:67:in start
/usr/lib/python2.7/dist-packages/nameko/utils.py:180:in spawning_method
/usr/lib/python2.7/dist-packages/eventlet/greenpool.py:238:in next
/usr/lib/python2.7/dist-packages/eventlet/greenthread.py:175:in wait
/usr/lib/python2.7/dist-packages/eventlet/event.py:121:in wait
/usr/lib/python2.7/dist-packages/eventlet/hubs/hub.py:294:in switch
/usr/lib/python2.7/dist-packages/eventlet/greenthread.py:214:in main
/usr/lib/python2.7/dist-packages/nameko/utils.py:175:in call
/usr/lib/python2.7/dist-packages/nameko/containers.py:198:in start
/usr/lib/python2.7/dist-packages/nameko/utils.py:180:in spawning_method
/usr/lib/python2.7/dist-packages/eventlet/greenpool.py:238:in next
/usr/lib/python2.7/dist-packages/eventlet/greenthread.py:175:in wait
/usr/lib/python2.7/dist-packages/eventlet/event.py:121:in wait
/usr/lib/python2.7/dist-packages/eventlet/hubs/hub.py:294:in switch
/usr/lib/python2.7/dist-packages/eventlet/greenthread.py:214:in main
/usr/lib/python2.7/dist-packages/nameko/utils.py:175:in call
/usr/lib/python2.7/dist-packages/nameko/messaging.py:191:in setup
/usr/lib/python2.7/dist-packages/nameko/amqp.py:43:in verify_amqp_uri
/usr/lib/python2.7/dist-packages/kombu/transport/pyamqp.py:116:in establish_connection
/usr/lib/python2.7/dist-packages/nameko/amqp.py:16:in __init__
/usr/lib/python2.7/dist-packages/amqp/connection.py:165:in __init__
/usr/lib/python2.7/dist-packages/amqp/connection.py:186:in Transport
/usr/lib/python2.7/dist-packages/amqp/transport.py:299:in create_transport
/usr/lib/python2.7/dist-packages/amqp/transport.py:95:in __init__
</pre>

It caused the service to crash.

Any ideas for what may cause this?

Env:
Centos 7
nameko 2.2.0
eventlet 0.18.4
amqp 1.4.9
kombu 3.0.35

**Comment by davidszotten** [comment]
i'd guess that your service is failing to connect to the rabbitmq broker. is rabbitmq running? is your service configured with the correct url to connect to it?

we should probably try to catch this and raise a more user-friendly error message

**Comment by genbits** [comment]
yes, it happened while running (a network hickup?)
how would you handle such cases?

**Comment by mattbennett** [comment]
The stack trace you've posted shows a service that is starting, not running. Service start is actually the only code path that `verify_amqp_uri` is called on.

If the network glitches while the service _is_ running, a few things may happen:

* Consumers will notice, and try to reconnect with backoff
* Publishers will notice immediately if publish-confirms are enabled, and sometime later if not. https://github.com/onefinestay/nameko/pull/337 adds support for this

**Comment by mattbennett** [comment]
I'm surprised `verify_amqp_uri` doesn't give a better error message in this case though

**Comment by mattbennett** [comment]
This is moot now `verify_amqp_uri` has been removed
