### ISSUE TITLE
Setting and getting message properties manually

### ISSUE THREAD

**Issue by sleighsoft** [nameko/nameko#374]
Is it possible to set and retrieve message properties in pub-sub manually?

**Comment by gitricko** [comment]
+1

**Comment by mattbennett** [comment]
This is a pretty regularly requested feature. It's been discussed in https://github.com/nameko/nameko/issues/292 previously.

#337 improves the situation slightly (by standardising the AMQP implementations to some extend) and I have some work in progress on top of that which exposes more message and delivery options. So watch this space.

**Comment by mattbennett** [comment]
There is a PR for this now: #456

**Comment by mattbennett** [comment]
Added in #456
