### ISSUE TITLE
Reading remote configuration

### ISSUE THREAD

**Issue by xqliang** [nameko/nameko#377]
Is it possible to read configuration from HTTP or a KV store (e.g. Consul, Redis) ?

**Comment by davidszotten** [comment]
Hi,

Not out of the box, but if you look in `nameko/cli/run.py`, it should be fairly straightforward to write a custom `main` that loads config from wherever and just passes that to `run`

**Comment by mattbennett** [comment]
It's also fairly easy to implement this outside of nameko.

At Student.com we use a combination of consul, confd and docker. When the docker containers start, confd pulls the latest config and generates the `config.yaml` file for the service.

**Comment by xqliang** [comment]
OK, thank you.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/reading-remote-configuration/315
