### ISSUE TITLE
Access environment variable as a non dependency provider

### ISSUE THREAD

**Issue by jgericke** [nameko/nameko#389]
Is it possible to read environment variables passed at runtime from within a service definition? It seems this is only possible as a dependency provider?

**Comment by kooba** [comment]
Dependency provider is the easiest way to get config values at the moment. It's quite trivial to get it going:

```
class Config(DependencyProvider):
    def get_dependency(self, worker_ctx):
        return self.container.config.copy()
```
and then in your service class:
```
class MyService(object):
    name = "my_service"
    config = Config()
```

Cheers.

p.s. please use Nameko mailing list for these types of questions:
https://groups.google.com/forum/#!forum/nameko-dev

**Comment by jgericke** [comment]
Thanks @kooba will limit any further queries to the mailing list :)

**Comment by mattbennett** [comment]
We should probably add this config DependencyProvider to the library, rather than having it reimplemented everywhere. I'll leave this issue open until we do that.

**Comment by mattbennett** [comment]
Thanks to @vmikki, this config DependencyProvider is now included in the library (https://github.com/nameko/nameko/pull/395)
