### ISSUE TITLE
consul & vault & ssl integration

### ISSUE THREAD

**Issue by asteven** [nameko/nameko#390]
We're building a cluster/infrastructure management platform and are considering to use nameko as our underlying microservice framework.

We already use vault and consul, so for me it would be natural to integrate our nameko based services with those for config and sercrets management.

Any thoughts on that from your side?
Currently I see 2 ways to pull this off.
1. we wrap nameko and override/patch where needed
2. we develop this in a way that it can be pushed upstream as an optional way to run/configure things

If aiming for 2. sounds reasonable for you I'd welcome hints on how to structure this so that you would  accept a patch upstream.

Currently I envision this would look something like this:
- start my nameko service, most likely dockerized
- pass it the url to consul
- my service resp. nameko grabs config from consul, ssl certs and rabbitmq credentials from vault
- then starts doing it's thing ;-)

Thoughts, Ideas, Comments?

**Comment by davidszotten** [comment]
Hi,

To get you started, you can just hook in your own config loader, and then hand off to existing nameko machinery

have a look at https://github.com/nameko/nameko/blob/master/nameko/cli/run.py

The command line entry point `nameko run` does the command line parsing and then hands off to `run(services, config, backdoor_port=None)` defined in that module. You can just write your own entry point that loads config from consul and then calls `run`

i guess this is more 1 than 2, though no patching should be required. 

in general, our config story isn't as good as we'd like it to be, so we might consider bringing this in, but if not, it should be easy to turn the above into a `nameko-consul` package to join the eco system.

**Comment by asteven** [comment]
Thanks for the pointers.

I'm wondering if the whole configuration could/should use the same or similar extension machinery as the rest.

e.g.
```sh
nameko run --config /path/to/file.yaml
   - use YamlConfigProvider
      - load the config file from disk
      - optionally monitor the file for changes and update or restart or whatever 

nameko run --config consul://127.0.0.1:8500/v1/kv/myservice/config
   - use ConsulConfigProvider
      - load config from the consul kv store
      - optionally could monitor kv store for changes
```
Browsing quickly through the code it seems it would not be that difficult to allow a ServiceContainer in concert with a ServiceRunner do something like this.

Anyway, just thinking out loud here.

For now I'll go with wrapping nameko to run under containerpilot.
Then do all the heavy lifting there and just restart the nameko service on changes.

In the meantime I have found your mailing list. Would send any future questions there instead of opening a ticket.

**Comment by mattbennett** [comment]
At Student.com we consul, docker and confd to push configuration loading "upstream". 

We run a container per service, and the container is built with `confd` and the required templates baked in. The `CMD` in our Dockerfile looks like:

```
CMD confd -onetime -backend consul ...; \
    . /appenv/bin/activate; \
    nameko run --config config.yaml app.service --backdoor 3000
```

`confd` fetches the latest configuration from consul and injects them into the template for `config.yaml`, updating the file if required.

When new config is available we just restart the service container.
