### ISSUE TITLE
How to add a custom serializer?

### ISSUE THREAD

**Issue by xqliang** [nameko/nameko#393]
I need a serializer to serialize dates in JSON format, how to add it for RPC entrypoint?

The `yaml` serializer can handle dates, but it's too slow.

**Comment by mattbennett** [comment]
You have to register it as a serializer with kombu. See https://github.com/nameko/nameko/blob/master/test/test_serialization.py#L176-L209 for an example.

**Comment by davidszotten** [comment]
if you have any further questions, feel free to post to the mailing list: https://groups.google.com/forum/#!forum/nameko-dev

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/how-to-add-a-custom-serializer/317
