### ISSUE TITLE
Helloworld error

### ISSUE THREAD

**Issue by minhhg** [nameko/nameko#403]
Hi,
I got the following error when run the standard helloworld.py in the docs.
System: Ubuntu 16.04, 64bits.

kombu                     3.0.35                   py27_0    local
nameko                    2.5.1                     <pip>
Python 2.7.12 :: Continuum Analytics, Inc
#========================================================
In [1]: n.rpc.greeting_service.hello(name="Minh")
#---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-53b2f0fd435c> in <module>()
----> 1 n.rpc.greeting_service.hello(name="Minh")

/home/minh/miniconda2/envs/nameko/lib/python2.7/site-packages/nameko-2.5.1-py2.7.egg/nameko/rpc.pyc in __call__(self, *args, **kwargs)
    392 
    393     def __call__(self, *args, **kwargs):
--> 394         reply = self._call(*args, **kwargs)
    395         return reply.result()
    396 

/home/minh/miniconda2/envs/nameko/lib/python2.7/site-packages/nameko-2.5.1-py2.7.egg/nameko/rpc.pyc in _call(self, *args, **kwargs)
    513 
    514             try:
--> 515                 producer.channel.returned_messages.get_nowait()
    516             except queue.Empty:
    517                 pass

AttributeError: 'Channel' object has no attribute 'returned_messages'

**Comment by mattbennett** [comment]
Can you please post the output of `pip freeze`?

**Comment by minhhg** [comment]
Hi,
Here is the output of pip freeze
=============================================
alabaster==0.7.9
amqp==1.4.9
anaconda-client==1.5.5
anyjson==0.3.3
awscli==1.11.13
Babel==2.3.4
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.5.1
billiard==3.3.0.23
bokeh==0.12.3
boto==2.43.0
botocore==1.4.70
Bottleneck==1.1.0
brewer2mpl==1.4.1
cashew==0.2.7
celery==3.1.23
cffi==1.9.1
chardet==2.3.0
chest==0.2.3
click==6.6
cloudpickle==0.2.1
clyent==1.2.2
colorama==0.3.7
colorlover==0.2.1
configparser==3.5.0
constantly==15.1.0
coverage==4.2
cryptography==1.6
cufflinks==0.8.2
cycler==0.10.0
Cython==0.25.1
dask==0.12.0
decorator==4.0.10
dexy==1.0.15
dexy-viewer==0.0.5
dill==0.2.5
docutils==0.12
enum-compat==0.0.2
enum34==1.1.6
et-xmlfile==1.0.1
eventlet==0.20.1
faulthandler==2.4
flake8==2.5.1
Flask==0.11.1
flower==0.9.1
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.0.5
gitdb2==2.0.0
GitPython==2.0.9
greenlet==0.4.11
h5py==2.6.0
HeapDict==1.0.0
idna==2.1
imagesize==0.7.1
incremental==16.10.1
inflection==0.3.1
ipaddress==1.0.17
ipdb==0.10.1
iptools==0.6.1
ipykernel==4.5.1
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
jdcal==1.3
Jinja2==2.8
jmespath==0.9.0
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.0
kombu==3.0.35
librabbitmq==1.6.1
linecache2==1.0.0
locket==0.2.0
log4mongo==1.5.0
logutils==0.3.3
lpsolve55==5.5.2.0
lxml==3.6.4
Markdown==2.6.7
MarkupSafe==0.23
matplotlib==1.5.3
mccabe==0.3.1
MDP==3.5
mistune==0.7.3
mock==2.0.0
multiprocess==0.70.4
nameko==2.5.1
nb-anacondacloud==1.2.0
nb-conda==2.0.0
nb-conda-kernels==2.0.0
nbconvert==4.2.0
nbformat==4.1.0
nbpresent==3.0.2
netCDF4==1.2.4
networkx==1.11
nose==1.3.7
nosexcover==1.0.10
notebook==4.2.3
numexpr==2.6.1
numpy==1.11.2
openopt==0.5625
openpyxl==2.4.0
pandas==0.19.1
paramiko==2.0.2
partd==0.3.6
path.py==10.1
pathlib2==2.1.0
pathos==0.2.0
patsy==0.4.1
pbr==1.10.0
pep8==1.7.0
pexpect==4.0.1
pickleshare==0.7.4
plotly==1.12.9
ply==3.9
pox==0.2.2
ppft==1.6.4.6
prompt-toolkit==1.0.9
ptyprocess==0.5.1
pudb==2016.2
py==1.4.31
pyasn1==0.1.9
pycairo==1.10.0
pycparser==2.17
pyflakes==1.3.0
Pygments==2.1.3
pykalman==0.9.5
pymongo==2.8
PyMySQL==0.7.9
pyparsing==2.1.4
pytest==3.0.4
pytest-faulthandler==1.3.1
python-dateutil==2.6.0
python-modargs==1.7
pytz==2016.7
PyYAML==3.12
pyzmq==16.0.2
qtconsole==4.2.1
Random123==0.0.0
requests==2.11.1
rope==0.9.4
rsa==3.4.2
s3transfer==0.1.9
scikit-learn==0.18.1
scikits.timeseries==0.91.3
scipy==0.18.1
seaborn==0.7.1
setproctitle==1.1.10
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
smmap2==2.0.0
snakefood==1.4
snowballstemmer==1.2.1
Sphinx==1.4.8
SQLAlchemy==1.1.4
statsmodels==0.6.1
tables==3.3.0
terminado==0.6
Theano==0.8.2
toolz==0.8.0
tornado==4.4.2
traceback2==1.4.0
traitlets==4.3.1
Twisted==16.5.0
unittest2==1.1.0
urwid==1.3.1
wcwidth==0.1.7
web.py==0.38
Werkzeug==0.11.11
widgetsnbextension==1.2.6
xarray==0.8.2
xlrd==1.0.0
XlsxWriter==0.9.3
xlwt==1.1.2
zope.interface==4.3.2

**Comment by mattbennett** [comment]
I think the problem is that you have `librabbitmq` installed, which doesn't support `basic_return`.

If librabbitmq is installed, kombu will use it in preference to py-amqp for any URIs beginning with `amqp://`. Nameko isn't compatible with librabbitmq. https://github.com/nameko/nameko/pull/361 updated most URIs to use the more explicit `pyamqp` scheme, but I guess we missed some usages in the CLI.

You can verify that librabbitmq is causing the problem adding `--broker pyamqp://<rabbitmq-uri>`to your `nameko run` and `nameko shell` commands.

**Comment by minhhg** [comment]
Yes, that is the case. Many thanks for your help. M

**Comment by mattbennett** [comment]
You're welcome. #404 updates all the defaults to avoid this happening again.
