### ISSUE TITLE
Pylint config for dependency providers

### ISSUE THREAD

**Issue by abulte** [nameko/nameko#414]
Hi,

I've playing with nameko for the past few days and so far I'm quite impressed with it, thanks!

I have one minor problem though: currently `pylint` is yelling at me when I use methods from dependency providers. For example, when using an injected `DatabaseSession` and calling `self.db.commit()` I get `E1101 Instance of DatabaseSession has no commit member`.

Is there a pylint trick you're aware of that would allow me to not ignore those errors on a line by line basis?

Thanks.

**Comment by mattbennett** [comment]
Glad you're enjoying Nameko :)

The linting errors are an unfortunate side-effect of dependency injection.

In an ideal world you'd be able to tell pylint that the attribute is actually an instance of a different type, but I don't know how to do that.

You can ignore specific lines though -- just add `# pylint: disable=no-member` or `# pylint: disable=E1101`. You can also disable the rule globally by running run pylint with the `--disable=no-member` flag, or via a pylintrc file.

**Comment by abulte** [comment]
Ok thanks. Can't wait for this ideal world to come true ;-)
