### ISSUE TITLE
Performance: one service worker can only process one task per second? 

### ISSUE THREAD

**Issue by Ryannnnnnn** [nameko/nameko#417]
I have a ServiceContainer with only one worker, as below:

```Python
config = {
        AMQP_URI_CONFIG_KEY:AMQP_URL,
        MAX_WORKERS_CONFIG_KEY: 1,
}
ServiceContainer(service_class, config)
```

After sending async calls, I started the service as the consumer. But it turns out that the only one worker can do exactly one task per second, is there something wrong with my configuration?

The service simply returns a number:

```Python
class Consumer(object):
    name = 'test'
    @rpc
    def work(self):
        logging.info('hello')
        return 42
```

logs:

```
[I 170314 20:39:25 main:26] hello
[I 170314 20:39:26 main:26] hello
[I 170314 20:39:27 main:26] hello
[I 170314 20:39:28 main:26] hello
[I 170314 20:39:29 main:26] hello
[I 170314 20:39:30 main:26] hello
[I 170314 20:39:31 main:26] hello
[I 170314 20:39:32 main:26] hello
[I 170314 20:39:33 main:26] hello
[I 170314 20:39:34 main:26] hello
[I 170314 20:39:35 main:26] hello
```

**Comment by mattbennett** [comment]
You're doing something wrong, but I can't tell what from what you've posted.

How are you running the service? And how are you calling it?

**Comment by Ryannnnnnn** [comment]
I think how I call the service is irrelevant, since I push hundreds of async RPC calls into queue all at once and just to see how service works.

The way I run the service is almost the same as `nameko run` (a.k.a. `nameko.cli.run.run()`) except that I call it manually (to rewrite the default `max_workers`). I posted the full demo [here](https://gist.github.com/Ryannnnnnn/ef898d155b824d29e7d710dc01da2bff).

**Comment by davidszotten** [comment]
i think there's a performance regression between `v2.4.3` and `v2.4.4`. even with 10 workers, there's a gap between each chunk of 10 being handled. still looking

**Comment by mikegreen7892003** [comment]
I work with @Ryannnnnnn .

There is a dead lock between `msg.ack` and `drain_events` while `container.max_workers` equals or large than `prefetch_count`.

e.g.

We set `max_workers = 1`, so `QueueConsumer.prefetch_count = 1`  and `consumer.qos(prefetch_count=self.prefetch_count)`. 

RabbitMQ with the `prefetch_count=1` will not delivery new message while the old one is not acked.

`msg.ack()` in `QueueConsumer._process_pending_message_acks` is called by `QueueConsumer.on_iteration` for each `drain_events` loop iteration.

So `drain_events` could not get new message util `on_iteration` called or time out. It will be time out after `safety_interval` seconds.


**https://github.com/nameko/nameko/blob/master/nameko/messaging.py**


```
    @property
    def prefetch_count(self):
        return self.container.max_workers
```

```
    def get_consumers(self, consumer_cls, channel):
           ******
            consumer.qos(prefetch_count=self.prefetch_count)
           ******
```

```
    def on_iteration(self):
        ******
        self._process_pending_message_acks()
        ******
```

```
    def on_iteration(self):
        ******
        self._process_pending_message_acks()
        ******
```

```
    def _process_pending_message_acks(self):
         ******
                msg.ack()
        ******
```

**https://github.com/celery/kombu/blob/master/kombu/mixins.py**

```
    def consume(self, limit=None, timeout=None, safety_interval=1, **kwargs):
        elapsed = 0
        with self.consumer_context(**kwargs) as (conn, channel, consumers):
            for i in limit and range(limit) or count():
                if self.should_stop:
                    break
                self.on_iteration()  # ack will be called here
                try:
                    conn.drain_events(timeout=safety_interval)
                except socket.timeout:
                    conn.heartbeat_check()
                    elapsed += safety_interval
                    if timeout and elapsed >= timeout:
                        raise
                except socket.error:
                    if not self.should_stop:
                        raise
                else:
                    yield
                    elapsed = 0
        debug('consume exiting')
```

**Comment by mikegreen7892003** [comment]
I suggest that
```Python
    @property
    def prefetch_count(self):
        return self.container.max_workers * 2
```

or prefetch_count could be configuable

**Comment by mikegreen7892003** [comment]
@davidszotten  I found that too.  `safety_interval` was changed between v2.4.3 and v2.4.4 .
Current implementation could process about `max_workers / safety_interval` messages per second.

**Comment by mattbennett** [comment]
@mikegreen7892003 @Ryannnnnnn thanks for the debugging!

Prefetch count should definitely be configurable. It was a mistake to tie it to `max_workers` because they're really distinct concepts -- for example, you may want to limit AMQP consumption without blocking other types of entrypoints (e.g. http).

Unfortunately it's not trivial to make `prefetch_count` configurable in the current implementation. You can do it with an override of the QueueConsumer, but you have to also override the RpcConsumer and Rpc entrypoint too:

``` python
class QueueConsumer(NamekoQueueConsumer):
    """ Subclass of :class::`nameko.messaging.QueueConsumer` so we can
        customise the ``prefetch_count`` value.
    """

    # override the property on nameko's QueueConsumer so that we can
    # write to the attribute in setup()
    prefetch_count = None

    def __init__(self, prefetch_count):
        self.custom_prefetch_count = prefetch_count
        super().__init__()

    def setup(self):
        super().setup()
        self.prefetch_count = self.custom_prefetch_count

    @property
    def sharing_key(self):
        return "{}-{}".format(type(self), self.custom_prefetch_count)

class RpcConsumer(NamekoRpcConsumer):
      queue_consumer = QueueConsumer(prefetch_count=...)

class Rpc(NamekoRpc):
     rpc_consumer = RpcConsumer()
```

I'd suggest *not* setting prefetch count to `self.container.max_workers * 2` unless `max_workers` is exactly one. Otherwise you risk taking consuming messages from the queue and having them block waiting for a worker to become available.

I've not made any attempt to fix the current implementation because I'd like to refactor away from the QueueConsumer altogether. There are a number of problems with the design, which you can read about here: https://groups.google.com/forum/#!topic/nameko-dev/WZ-xRYd2-vw

For your specific case of restricting to a single thread, I'd set `max_workers` (and `prefetch_count`) to something >1 and put a lock/semaphore around the work you want to serialise.

**Comment by davidszotten** [comment]
Unless you have a re-write in progress, i think we need to look at ways to reverse this regression. Having the out-of-the-box defaults capped at 10 requests/second isn't great

**Comment by mattbennett** [comment]
@davidszotten it's not exactly a regression in 2.4.4 -- the change there just makes the problem more obvious. This behaviour has been present forever, and it's intrinsic in the way the kombu consumer works.

Example using Nameko 2.4.0:

``` python
# service.py
from nameko.rpc import rpc
import logging

class Consumer(object):
    name = 'test'
    @rpc
    def work(self):
        logging.info('hello')
        return 42
```

``` yaml
# config.yaml

AMQP_URI: "pyamqp://guest:guest@localhost:5672/"
max_workers: 1

LOGGING:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: "%(asctime)s: %(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simple
    root:
        level: INFO
        handlers: [console]
```

```
(tmp-1ce58f0405f7905b)Matts-13-inch-Macbook-Pro:tmp mattbennett$ nameko run service --config config.yaml
2017-03-16 11:07:07,832: starting services: test
2017-03-16 11:07:07,858: Connected to amqp://guest:**@127.0.0.1:5672//
2017-03-16 11:07:07,871: hello
2017-03-16 11:07:07,978: hello
2017-03-16 11:07:08,081: hello
2017-03-16 11:07:08,183: hello
2017-03-16 11:07:08,288: hello
2017-03-16 11:07:08,392: hello
2017-03-16 11:07:08,497: hello
2017-03-16 11:07:08,601: hello
2017-03-16 11:07:08,713: hello
2017-03-16 11:07:08,816: hello
2017-03-16 11:07:08,920: hello
2017-03-16 11:07:09,025: hello
2017-03-16 11:07:09,129: hello
```

I'll do a similar test with the kombu consumer on its own, but I think @mikegreen7892003 is right -- it's limited to `max_workers` / `safety_interval` messages per second.

**Comment by davidszotten** [comment]
well `max_workers / safety_interval` changed by 10x, going from what i might consider "acceptable out of the box" of 100/s to less so at 10/s

**Comment by mikegreen7892003** [comment]
@mattbennett  @davidszotten 
Thanks for your review.

`max_workers / safety_interval` limitation is because the messages are acked by nameko every `drain_events`.
To fix the problem quickly, we could simply set `prefetch_count` **larger** than `max_workers`, e.g. `max_workers + 1` could be a reasonable option.

Our fixture is following,
```Python
from nameko.messaging import QueueConsumer

@property
def prefetch_count(self):
    return self.container.max_workers + 1
```

I agree with @mattbennett  and think the problem is intrinsic.

e.g.

I modify [the code](https://gist.github.com/mattbennett/30cc95d42346df62a60e) of @mattbennett with `prefetch_count = 1` and `GreenPool(size=2)`. The code will process **one message per second**.

**publisher.py**
```Python
# coding=utf-8
import eventlet
eventlet.monkey_patch()

import logging
from tornado.options import parse_command_line
parse_command_line()
from eventlet.greenpool import GreenPile
from kombu.pools import producers
from kombu import Exchange, Queue

exchange = Exchange('exchange', type='direct')
queue = Queue('queue', exchange, routing_key='queue')


if __name__ == '__main__':
    from kombu import Connection

    connection = Connection('amqp://guest:guest@localhost')

    def publish(index):
        with producers[connection].acquire(block=True) as producer:
            producer.publish(index, routing_key='queue', serializer='json')

    pile = GreenPile()
    for index in xrange(100):
        pile.spawn(publish, index)
    list(pile)
```

**consumer.py**
```Python
# coding=utf-8
import eventlet
eventlet.monkey_patch()

import logging
from tornado.options import parse_command_line
parse_command_line()

import time
import threading

from eventlet.greenpool import GreenPool
from kombu.mixins import ConsumerMixin
from kombu.log import get_logger
from kombu import Exchange, Queue
from kombu import Connection

exchange = Exchange('exchange', type='direct')
queue = Queue('queue', exchange, routing_key='queue')

pool = GreenPool(size=2)


class Worker(ConsumerMixin):
    def __init__(self):
        self._message_to_ack = []

    def on_iteration(self):
        message_list = self._message_to_ack
        self._message_to_ack = []
        for message in message_list:
            message.ack()

    @property
    def connection(self):
        return Connection('amqp://guest:guest@localhost', heartbeat=60.0)

    def handle_message(self, body, message):
        logging.info("CONSUME %s in %s", body, threading.current_thread().get_name())
        gt = pool.spawn(self.process_task, body, message)

    def get_consumers(self, Consumer, channel):
        consumer = Consumer(queues=[queue],
                            accept=['json'],
                            callbacks=[self.handle_message])
        consumer.qos(prefetch_count=1)
        return [consumer]

    def process_task(self, body, message):
        logging.info("ACK %s in %s", body, threading.current_thread().get_name())
        self._message_to_ack.append(message)

if __name__ == '__main__':
    try:
        worker = Worker()
        pool.spawn(worker.run).wait()
    except KeyboardInterrupt:
        print('bye bye')
```

**Comment by mattbennett** [comment]
@davidszotten I agree that we need to do something in the short term.

I like @mikegreen7892003's suggestion of setting `prefetch_count = max_workers + 1`. It breaks the deadlock sufficiently but leaves at most one message blocked on the worker pool.

The same example I ran earlier with that implemented (`max_workers = 1`, `prefetch_count = 2`):

```
2017-03-16 13:24:24,224: starting services: test
2017-03-16 13:24:24,246: Connected to amqp://guest:**@127.0.0.1:5672//
2017-03-16 13:24:24,269: hello
2017-03-16 13:24:24,289: hello
2017-03-16 13:24:24,292: hello
2017-03-16 13:24:24,294: hello
2017-03-16 13:24:24,296: hello
2017-03-16 13:24:24,298: hello
2017-03-16 13:24:24,301: hello
2017-03-16 13:24:24,303: hello
2017-03-16 13:24:24,305: hello
2017-03-16 13:24:24,308: hello
```

And with 1000 requests and default values (`max_workers = 10`, `prefetch_count = 11`):

```
2017-03-16 13:35:37,076: starting services: test
2017-03-16 13:35:37,095: Connected to amqp://guest:**@127.0.0.1:5672//
2017-03-16 13:35:37,107: hello
<snip>
2017-03-16 13:35:39,379: hello
```

(~500 reqs/sec.)

**Comment by davidszotten** [comment]
agreed. @mikegreen7892003 would you like to make a pr bumping it to `max_workers + 1`? (if not, i'm happy to but it was your idea)

**Comment by mikegreen7892003** [comment]
@davidszotten  Thanks for your advise.
I write a PR with the modification and explain why.

**Comment by davidszotten** [comment]
thanks for finding and the suggested fix!

**Comment by davidszotten** [comment]
hi. in case you've not been following the recent discussions you may be interested in https://github.com/nameko/nameko/pull/429#issuecomment-294789346 and the subsequent release of `2.5.4`
