### ISSUE TITLE
"Acquire on closed pool" when making RPC call

### ISSUE THREAD

**Issue by richardasaurus** [nameko/nameko#423]
When making an rpc call locally I don't get this error, however once deployed I do:

```
# rpc call happens here at the top, within get_thing()
 File "app/clients/thing_service.py", line 106, in get_thing
    thing_id=thing_id,
  File "nameko/rpc.py", line 394, in __call__
    reply = self._call(*args, **kwargs)
  File "nameko/rpc.py", line 492, in _call
    with get_producer(self.amqp_uri, self.use_confirms) as producer:
  File "python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "nameko/amqp.py", line 75, in get_producer
    with producers[conn].acquire(block=True) as producer:
  File "kombu/connection.py", line 883, in acquire
    R = self.prepare(R)
  File "kombu/pools.py", line 63, in prepare
    conn = self._acquire_connection()
  File "kombu/pools.py", line 38, in _acquire_connection
    return self.connections.acquire(block=True)
  File "kombu/connection.py", line 874, in acquire
    raise RuntimeError('Acquire on closed pool')
```

Also If i ssh into the server this is happening on and use `nameko shell` to make the same rpc call, ti works every time.

Has anyone experienced this before or has any idea of what the issue could be? Thanks

kombu==3.0.37
nameko==2.5.1
Python 3.6.1

**Comment by richardasaurus** [comment]
Additionally getting this error if that's relevant at all. Although th

`ChannelNotOpen "Channel.close: (504) CHANNEL_ERROR - expected 'channel.open'"`

**Comment by mattbennett** [comment]
I've not seen this before, but we're not running on Python 3.6. Actually I'm pretty sure nameko's test suite does not pass against 3.6.

**Comment by richardasaurus** [comment]
Closing this as the issue was running 2 rabbit instances behind HAProxy. So the fix was to just have one rabbit instance for now. 

Also everything seems to work in python 3.6
