### ISSUE TITLE
rcp: allow to return promise instead of forcefully synchronous result()

### ISSUE THREAD

**Issue by ornoone** [nameko/nameko#424]
It can be a good integration to add the support for returning Promise for rpc call, along with synchronous result. 

for now, it seem we can do: 
```python
with ClusterRpcProxy(config) as cluster_rpc:
    set_handler_for_events()
    hello_res = cluster_rpc.service_x.remote_method.call_async("hello")
    hello_res.result()
    teardown_handler()


````
but if we don't care for the result, but must run some code (cleanup?) after the rpc is finished, without blocking the whole function, it would be nice to do 
```
with ClusterRpcProxy(config) as cluster_rpc:
    set_handler_for_events()
    hello_res = cluster_rpc.service_x.remote_method.call_async("hello")
    promise = hello_res.promise()
    @promise.then
    def after():
        teardown_handler()
```

this should add a `promise` method to `RpcReply`  which return a Promise (generic). 

I don't know how to do without blocking. but it seem a good use case.

**Comment by ornoone** [comment]
I just wrote some snippet to achieve this via `promise` python package: 

```python
import eventlet
from promise.promise import Promise

def make_promise(result_async):
    def promise_caller(resolve, reject):
        def promise_waiter():
            resolve(result_async.result())  # will wait for rcp reply
        eventlet.spawn(promise_waiter)
    return Promise(promise_caller)


with ClusterRpcProxy(config) as cluster_rpc:
    set_handler_for_events()
    hello_res = cluster_rpc.service_x.remote_method.call_async("hello")
    promise = make_promise(hello_res)
    @promise.then
    def after(result):
        teardown_handler()
```

**Comment by mattbennett** [comment]
I think the snippet you have here is a perfectly good solution, and it's better for it to live in your application (tailored to your particular use-case) than to become part of the framework.

**Comment by ornoone** [comment]
thanks for the fast reply :smile: .

it's true and I understand why you want to keep it outside the framework, but it may be a good idea to integrate some snippet like this to the doc, showing how nameko can be used along with differents patterns.
