### ISSUE TITLE
Fixed version of eventlet

### ISSUE THREAD

**Issue by mohamedrez** [nameko/nameko#425]
ref:
https://github.com/nameko/nameko/blob/master/setup.py#L24

the release v0.20.1 of eventlet breaked our build, I think it's more safe to specify a version instead of `>=`

**Comment by mat10tng** [comment]
:+1:  , I also have this problem. If you manual install eventlet==v.20.0 then it started to working again.

**Comment by davidszotten** [comment]
i've seen builds with `0.20.1` pass on travis. do you have an example of what doesn't work?

**Comment by mat10tng** [comment]
Yes, of course, log file is included. I had multiple service run with docker and every service are hit with the same kind of errors when rebuild without specify the eventlet version.

## log
[log.txt](https://github.com/nameko/nameko/files/904072/log.txt)
## requirement
nameko==2.5.2

## dockerfile
FROM python:2.7
ENV PYTHONUNBUFFERED 1

RUN mkdir /module
COPY compose/requirements/ /module/compose/requirements/
RUN pip install -r /module/compose/requirements/dev --cache-dir /pip-cache

EXPOSE 5000

## run 
nameko run --config config.yml service --backdoor 3000

**Comment by davidszotten** [comment]
thank you

as a library, we try to keep our requirements as open as possible, so that application developers can choose the versions that best work for them. the downside of this is, as you noted, that we are more susceptible to upstream dependencies causing issues. if this becomes a problem we can (and do) exclude or pin down certain versions (currently kombu is pinned below 4)

i'm not yet sure of the scope of this particular issue, but if needed we can pin down eventlet. in the mean time i've raise https://github.com/eventlet/eventlet/issues/401

thanks again for the report

**Comment by mohamedrez** [comment]
Thanks @davidszotten there is only one thing that I want to add, It was very difficult for us to debug because the error was thrown on:
`from django_dynamic_fixtures import G`
the log was showing:
`E   RuntimeError: no suitable implementation for this system`
we started reviewing our requirement.txt file and nothing was changed, then we realized that the setup of nameko was specifying a none fixed release dependency.

**Comment by stevebasher** [comment]
Specifying `eventlet==0.20.0` within my `requirements.txt` fixed this issue for me.

**Comment by davidszotten** [comment]
Hi all,

a patch has been merged into eventlet and the author (@temoto) is asking people to help validate that it fixes the problem. if you have a chance, please reply to [his comment](https://github.com/eventlet/eventlet/issues/401#issuecomment-325128613)

**Comment by temoto** [comment]
Please use this version for testing

`pip install https://github.com/eventlet/eventlet/archive/b756447bab51046dfc6f1e0e299cc997ab343701.zip`

**Comment by mattbennett** [comment]
Nameko is now compatible with more modern versions of eventlet in which this bug has been fixed
