### ISSUE TITLE
ZeroMQ support

### ISSUE THREAD

**Issue by vartagg** [nameko/nameko#454]
Sometimes RabbitMQ is overkill. How about ZeroMQ support in nameko?

**Comment by mattbennett** [comment]
It is certainly possible to implement a set of extensions that use ZeroMQ as the transport. I imagine RPC and Events would translate quite well.

The basic requirements for implementing an entrypoint are:

- Inherit from `nameko.extensions.Entrypoint`
- Listen to some socket, queue or other source of messages
- Call `container.spawn_worker` when an appropriate message is received

A nice and simple example of an custom entrypoint is https://github.com/iky/nameko-slack. For a more complex example, check https://github.com/Overseas-Student-Living/nameko-bayeux-client

Implementing a dependency provider (e.g. a ZeroMQ-backed RPC proxy) is even easier:

- Inherit from `nameko.extensions.DependencyProvider`
- Implement the `get_dependency()` method to return an appropriate interface for the service to use the downstream dependency.

A simple example of a custom dependency provider is https://github.com/onefinestay/nameko-sqlalchemy.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/zeromq-support/303
