### ISSUE TITLE
Standalone RPC issue when using stevedore - RuntimeError: This consumer has been stopped, and can no longer be used

### ISSUE THREAD

**Issue by bobh66** [nameko/nameko#461]
I'm using stevedore extensions to load classes that use standalone ClusterRpcProxy to invoke microservices.  The RPC methods are called from a Flask wrapper framework.  

For example:

    class MyTestClass()
        proxy = ClusterRpcProxy(CONFIG)

        def services_ping(self):
            try:
                with self.proxy as rpc:
                   return rpc.services.ping()
            except UnknownService:
                return 404

The service works fine the first time it is called (via REST API), but all calls after that fail with:

`File "/usr/lib/python3.4/site-packages/nameko/standalone/rpc.py", line 53, in wait
    "This consumer has been stopped, and can no longer be used"
RuntimeError: This consumer has been stopped, and can no longer be used`

The interesting thing is that the AMQP message IS sent to the far end and the far end replies, but the consumer doesn't wait around for the reply because it thinks it has been stopped.

The problem seems to be that the "stopped" flag for PollingQueueConsumer is set to False in the __init__() method, which is called when the class is instantiated by stevedore.  It works fine for the first invocation of the service, and the stopped flag is set to "True" when the proxy finishes in unregister_provider().

Then when the service is called again, the __init__() class is not called because the proxy already exists, the request gets sent, but the error occurs because stopped was not reset to False by register_provider()

The fix seems to be to set self.stopped to False in register_provider() rather than in __init__() so the PollingQueueConsumer knows that the consumer has started again and will wait for the response to the message.

I'll push a PR for review.

**Comment by bobh66** [comment]
Created PR https://github.com/nameko/nameko/pull/462 for this issue.

**Comment by mattbennett** [comment]
Fixed by https://github.com/nameko/nameko/pull/462. Thanks!
