### ISSUE TITLE
About WsgiApp with CORS

### ISSUE THREAD

**Issue by lagelalegal** [nameko/nameko#471]
Now, we use `http` decorator only support one method.
```python
@http('GET', '/hello')
def xxxx(self, request):
    pass
```

Why I need multiple methods support？

Because of that I use `put` or `post` method in browser, It have a default method with 'options' been caused. 

It's base on `CORS`.

**Comment by davidszotten** [comment]
it's not very well documented yet unfortunately, but did you know that the following is currently possible:

```
    @http('GET', '/multiple')
    @http('POST', '/multiple')
     def method(self, request):
         return 200, request.method
```

**Comment by lagelalegal** [comment]
Thank you very much, It's my fault.
Handle the `CORS` on browser, It's not good idea.
So I want to write it on config _yaml file.

**Comment by kooba** [comment]
@lagelalegal have you looked at this extension? https://github.com/harel/nameko-cors as an example of cors support?

**Comment by lagelalegal** [comment]
@kooba good, thank you very much.

**Comment by davidszotten** [comment]
wanna add it the the `community-extensions` list? (which is on master but not yet on "stable" which is default on readthedocs :(

**Comment by kooba** [comment]
I'm bit worried about adding anything without tests to that list 😄 ... I might open PR against `nameko-cors` with some tests first 😉

**Comment by lagelalegal** [comment]
Do you want add `nameko-cors` into [community-extensions](http://nameko.readthedocs.io/en/stable/community_extensions.html)? I think I must remind the [nameko-cors](https://github.com/harel/nameko-cors) author at first.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/about-wsgiapp-with-cors/311
