### ISSUE TITLE
How to do some setup before starting any entrypoint

### ISSUE THREAD

**Issue by xqliang** [nameko/nameko#482]
I want to do some process setup before starting any entrypoint, such as loading data from database  to local memory via [nameko-sqlalchemy DependencyProvider](https://github.com/onefinestay/nameko-sqlalchemy).

But the nameko-sqlalchemy is a DependencyProvider, and I can't create a new DependencyProvider rely on it.

Can you introducing an initialization class method, which will be execute after all DependencyProvider started and before starting any EntryPoint?

**Comment by mattbennett** [comment]
`DependencyProvider.setup` or `DependencyProvider.start` is the place to do this. You can subclass the nameko-sqlalchemy DependencyProvider to implement or override these methods:

``` python
from nameko_sqlalchemy import DatabaseSession

class MemoryLoadingDatabaseSession(DatabaseSession):
    def start(self):
        session_cls = sessionmaker(bind=self.engine)
        session = session_cls()
        ...  # load data into memory
        session.close()
```

**Comment by xqliang** [comment]
But how to load data from database to another dependency, such as [Redis](https://github.com/etataurov/nameko-redis)?

**Comment by kooba** [comment]
I think you want to call dependency provider before entrypoint fires, maybe this will help:

```python
import wrapt
import pytest
import inspect
import json

from nameko.dependency_providers import DependencyProvider
from nameko.web.handlers import http


class DataLoader:

    def __init__(self, client):
        self.client = client

    def load_data(self, wrapped, foo=None):
        @wrapt.decorator
        def wrapper(wrapped, instance, args, kwargs):
            self.client("loading data from external source {}".format(foo))
            return wrapped(*args, **kwargs)
        return wrapper(wrapped)


class MyDependency(DependencyProvider):

    def start(self):
        """Any setup for data store client session"""
        self.client = lambda message: print(message)

    @staticmethod
    def load_data(foo=None):
        def find_loader(instance):
            """Find instance of our DependencyProvider,
                 what is returned from get_dependency
            """
            data_loader = inspect.getmembers(
                instance, lambda obj: isinstance(obj, DataLoader))
            return data_loader[0][1]

        @wrapt.decorator
        def wrapper(wrapped, instance, args, kwargs):
            decorated = find_loader(instance).load_data(wrapped, foo=foo)
            return decorated(*args, **kwargs)
        return wrapper

    def get_dependency(self, worker_ctx):
        return DataLoader(self.client)


class MyService:

    name = 'my_service'

    data_dependency = MyDependency()

    @http('GET', '/foo')
    @data_dependency.load_data(foo='bar')
    def my_http_endpoint(self, request):
        return json.dumps({'ok': True})


@pytest.fixture
def web_session(container_factory, config, web_session):
    container = container_factory(MyService, config)
    container.start()
    return web_session


def test_will_load_data_from_before(web_session):
    response = web_session.get('/foo')
    assert response.status_code == 200
```

Example above creates dependency provider that exposes `@data_dependency.load_data` decorator you can use on every entrypoint.

Please checkout [Community Extension](https://nameko.readthedocs.io/en/stable/community_extensions.html) page for example of Redis dependency providers.

**Comment by xqliang** [comment]
Thank you for your answer, but there is still a small problem, I hope only doing the heavy initialization once at program startup time, because the heavy initialization will slow down the first batch of concurrent requests.

**Comment by kooba** [comment]
All heavy initialization should happen in `def start(self):` method. It will be run only once during the start of your service.

**Comment by mattbennett** [comment]
@xqliang I think we need to know exactly what your desired outcome is.

From what I understand above, you want to extract some data from a relational database and insert it into Redis, and you want to do it only once and when the service starts. Is that correct?

If so, there are a couple of options. You could create a new `DependencyProvider` that talks to both the relational database _and_ redis, and put the load/insert code in its `start()` method. Or you could use the existing nameko-sqlalchemy and nameko-redis DependencyProviders and do the load/insert in a service method. There is [an entrypoint](https://github.com/nameko/nameko/blob/3f0209a36bc9610bdee926db057f0d716dd0bc19/nameko/testing/services.py#L474) in `nameko.testing.services` which fires exactly once, when the service starts.

**Comment by xqliang** [comment]
> From what I understand above, you want to extract some data from a relational database and insert it into Redis, and you want to do it only once and when the service starts. Is that correct?

You are right.

> You could create a new DependencyProvider that talks to both the relational database and redis.

I can create a new DependencyProvider, but then I can't reuse existing nameko-sqlalchemy and nameko-redis.

Look at the following example code, I already have a `session` and `cache` instance, and I wan't reuse them to do the heavy initialization once before running any entrypoint.

~~~python
from nameko.rpc import rpc
from nameko_sqlalchemy import Session
from nameko_redis import Redis

from .models import Model, DeclarativeBase


class Service(object):
    name = 'service'
    session = Session(DeclarativeBase)
    cache = Redis('cache')

    def init(self):
            data = self.session.query(Model).get(id=1)  # heavy operater
            self.cache.set('heavy_initialization_data', data)
            return data

    # def run_once_before_entrypoint_and_after_dependency(self): 
    #     self.init()

    @rpc
    def hello(self):
        data = self.cache.get('heavy_initialization_data')
        if data is None:
            data = self.init()
        return data
~~~

> There is an entrypoint in nameko.testing.services which fires exactly once, when the service starts.

This is great, but we can not make sure the running once entrypoint start before others entrypoint (such as the `hello` in above example code), so it still may slow down the first batch of concurrent requests?

**Comment by mattbennett** [comment]
Nameko doesn't have any kind of built-in hook for this. I have wondered in the past whether a "hook registration" system might be useful, to allow arbitrary code to be executed at different service states (e.g. before/after service code loaded, dependencies started etc.) but there isn't anything like this at the moment.

If you really want to do this you have the option of using a custom `ServiceContainer` class, which could start dependencies, then call your hook, then start entrypoints. Writing a custom DependencyProvider would probably be easier though.

**Comment by xqliang** [comment]
@mattbennett OK, thank you.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/how-to-do-some-setup-before-starting-any-entrypoint/301
