### ISSUE TITLE
Connecting multiple rabbitmq host from Nameko

### ISSUE THREAD

**Issue by singhmanish09** [nameko/nameko#498]
What is the mechanism through which nameko can connect to multiple rabbitmq host configured in mirrored mode so that HA can be achieved using it.

**Comment by mattbennett** [comment]
Most people put a load-balancer in front of the RabbitMQ nodes. Another approach is to pass a semicolon delimited string with the addresses of each node as the AMQP_URI, e.g.

``` yaml
AMQP_URI: pyamqp://guest:guest@rabbitmq1:5672/;pyamqp://guest:guest@rabbitmq2:5672/
```

This passes through to Kombu, which will round-robin between URIs when it can't connect.

HA strategies in general have been covered on the mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/nameko-dev/HA%7Csort:date/nameko-dev/DpR8LeNUod0/uOethL81AgAJ

**Comment by sammy200592** [comment]
Hi Matt,

I tried the method you suggested:

**AMQP_URI: amqp://guest:guest@localhost:562/;amqp://guest:guest@localhost:5672/**

This works fine when my first port address is set to the correct port i.e 5672 but it gives me an error when the first port is wrong and the second port is right just like in the case above.

I am trying this for the Nameko service and getting the following error:
**OSError: [Errno 61] ECONNREFUSED**

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/connecting-multiple-rabbitmq-host-from-nameko/293
