### ISSUE TITLE
Custom entrypoints

### ISSUE THREAD

**Issue by WoLfulus** [nameko/nameko#503]
I'm trying to automate some documentation on my services, and I'm struggling to get things to work. I'm new to nameko, only used it for testing and I'm feeling a little lost to get something more advanced like this to work. 

Problem is that I have no idea where/how to collect class and method information to get the data I need: the closest thing I got was to write a `class Documentation(Rpc)` and `rpc = Documentation.decorator` and use that decorator instead to access the service class with `self.container.service_cls`, but it seems that it executes for every method, and I need to group the information up. Also I have no idea how I could access the Documentation instance inside the action later.

In resume, what I want to accomplish it:

- Write a normal service
- Do something really simple if needed to the service (like a dependency `docs = Documentation()`)
- A new rpc method "documentation" will be added automatically (without writing additional code) and it should return the docstrings from the class and its methods
- Should be able to call n.rpc.myservice.documentation() and get the data I need

# Example

### How service is written

```python
class Service:
    """a docstring"""
    name = "myservice"

    @rpc
    def test(self):
        """another docstring"""
        return True
```

### How service will behave like

```python
class Service:
    """a docstring"""
    name = "myservice"

    @rpc
    def test(self):
        """another docstring"""
        return True

    @rpc
    def documentation(self):
        return { 
            "service": "a doc string",
            "methods": {
                "test": "another docstring", 
            }
        }
```

Thoughts?

**Comment by WoLfulus** [comment]
Awesome! 

But how do I manually register an entrypoint? Just setting the nameko_entrypoints makes nameko detect it? As I was reading the code, I do need to wrap/extend the service with several base classes right?

I tried extending the service class with another class (that has the @rpc documentation method) and it doesn't work because nameko tries to register both services.

**Comment by davidszotten** [comment]
extending should work, but you may have to be more specific with the runner, `nameko run module:ServiceClass`

**Comment by WoLfulus** [comment]
Nice! I'll give it a try!

**Comment by davidszotten** [comment]
for future reference, [the mailinglist](https://groups.google.com/forum/#!forum/nameko-dev) is probably a better place for questions like this. thanks

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/custom-entrypoints/300
