### ISSUE TITLE
how to deal with long running task 

### ISSUE THREAD

**Issue by jackytu256** [nameko/nameko#506]
Hi author,
     I am looking for one way to cope with long running task , such as preprocessing large videos ( at least 2 hours).  Cloud you please give me some tips to help me to solve this task?  

 Thanks!

**Comment by mattbennett** [comment]
This is way too broad a question to give any meaningful recommendations. If you have a specific question or design in mind I may be able to help. You may also find that the [mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/nameko-dev) is more responsive.
