### ISSUE TITLE
Why did nameko use RPC for Communication between Service?

### ISSUE THREAD

**Issue by radiegtya** [nameko/nameko#509]
I think this is not issue, rather than just a question. Why did nameko use RPC for Communication between Service? Is there any issue when using REST? or RPC much faster for this communication purpose? Sorry I am newbie at microservices

**Comment by mattbennett** [comment]
The main reason is that RPC is simple. It can be invoked just like a "normal" method and is very flexible in terms of what the server can offer. Unlike REST it doesn't force you to write your APIs in a particular way.

There's a good (tongue-in-cheek) article about it here: https://medium.freecodecamp.org/rest-is-the-new-soap-97ff6c09896d

**Comment by kooba** [comment]
RPC over RabbitMQ, as implemented in Nameko, gives you service discovery for free where you can have multiple services handling RPC requests effortlessly. Additionally Nameko comes with [HTTP endpoint](https://nameko.readthedocs.io/en/stable/built_in_extensions.html#http) (based on werkzeug) which lets you build any REST APIs you'd like.

**Comment by codebase02** [comment]
Does nameko only support RPC over *MQ, not raw RPC?  If I have an existing RPC server, and I want to use nameko just for the RPC client, is that possible?

thanks.

**Comment by mattbennett** [comment]
"RPC" just means Remote Procedure Call. It doesn't imply an implementation or even a protocol. You'll only be able to talk to your "existing RPC server" using whatever protocol it uses.

You could build an extension in Nameko that implemented whatever protocol that is so your Nameko service could speak it, but you can't just use the built-in AMQP client unless your remote server is listening for Nameko AMQP RPC.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/why-did-nameko-use-rpc-for-communication-between-service/304
