### ISSUE TITLE
yaml env_var parsing with } in default value

### ISSUE THREAD

**Issue by ornoone** [nameko/nameko#510]
Hi, I found an unexpected behavior with env_var parsing in config.

it's great to natively add env variable into configuration, but I found some exemples where it behavior is not what expect.

## default value with '}' char
``${XML_PUBLISHER_URL:www.example.com/{ref}/}`` => ``www.example.com/{ref/}``
we use this config to give a python template using str.format ({ref} key) . the env_var parser will stop at the first '}' occurence and will give us 

## nested env_var token
`` ${XML_PUBLISHER_URL:www.example.com/${XML_PATH:/xml/}all.xml}`` => `` 'www.example.com/${XML_PATH:/xml/all.xml}'``

as is saw in the code, the env_var_constructor in cli/main.py use a regex which match the first closing bracket.

I will see if a recursive regex can help solve these issues and allow for a recursive env_var replacement for default value.

**Comment by ornoone** [comment]
after some search, I have found a regex which work and solve both cases: 

```regex
\$\{(?:([^{}:\s]+)(?::(.*(?R)?.*))?)*(?<!\\)\}
```
check it at [regex101.com](https://regex101.com/r/CEvpT4/1)

it seem to solve the problem of the «first }» occurrence by a «last }» occurrence. but it support a \ escape char for «}».

it will solve the problem of nested env_var support if the function 

todo for implementation: 
- use regex module (from pypi) instead of builtin re, since re don't support recursive regex `(?R)`
- replace escaped `\}` after parsing to set it back to `}`
- maybe change env_var_constructor to support nested resolver ?

**Comment by mattbennett** [comment]
Thanks @ornoone, this seems like a useful addition. 

The only thing I'm slightly cautious of is forcing users to accept another library dependency. If we can make the use of the `regex`library optional I would be in favour of accepting this feature.

Do you want to make a PR with your suggested implementation?

**Comment by ornoone** [comment]
hi @mattbennett , I will work on it and will take care of your dependency concern.

**Comment by mattbennett** [comment]
Implemented in #515
