### ISSUE TITLE
I wrote Twilio and SendGrid dependency providers

### ISSUE THREAD

**Issue by raybotha** [nameko/nameko#519]
Hi, I wrote a simple dependency provider for the Twilio client for SMS and Voice.

It's on PyPi as nameko-twilio and the GitHub is here https://github.com/invictuscapital/nameko-twilio/

My company will be using it in production.

I've also made one for SendGrid: https://github.com/invictuscapital/nameko-sendgrid

**Comment by raybotha** [comment]
I've also made one for SendGrid: https://github.com/invictuscapital/nameko-sendgrid

**Comment by mattbennett** [comment]
Nice. Want to raise a PR to add these to the  [community extensions](https://github.com/nameko/nameko/blob/master/docs/community_extensions.rst) page?

**Comment by raybotha** [comment]
Cool, done: https://github.com/nameko/nameko/pull/523

**Comment by mattbennett** [comment]
Thanks @raybotha
