### ISSUE TITLE
Nameko service event_handler as a PULL job worker

### ISSUE THREAD

**Issue by rizplate** [nameko/nameko#522]
1- Can the event.handler/pub-sub be used as a job worker?
i.e. instead of nameko pushing the event to the service.handler, can the service *pull* the message so as to implement a pull based events? 

2- If one event.handler event-let is taking 1 hr to complete? is every other event waiting to be delivered? i.e. none of other event.handler will run or does event-let primitively _pause_ the green-thread and give resources to other green-threads? I think resource hogger event.handler will block the whole system. any way around it?

3- Can you explain the message data flow of inbound and outbound calls of rpc i.e. which objects of nameko are doing what when the message is received.

**Comment by mattbennett** [comment]
> 1- Can the event.handler/pub-sub be used as a job worker?

Not sure what you mean by "job worker" here. Actually services _do_ pull messages from the broker, even event handlers, but perhaps what's not obvious is that they pull up to a certain amount at a time (the "prefetch count"). By default in Nameko this value is inherited from the `max_workers` config value, which is `10`.

You can make your services look more like workers that "pull" work when the existing work is done by reducing the value of `max_workers`.

Have I understood the question correctly?

2- If one event.handler event-let is taking 1 hr to complete? is every other event waiting to be delivered? i.e. none of other event.handler will run or does event-let primitively pause the green-thread and give resources to other green-threads? I think resource hogger event.handler will block the whole system. any way around it?

Eventlet will yield any thread that blocks for I/O, so unless your " resource hogger" thread is unyielding then other threads will still run. If you have a workload that _is_ unyielding, you should delegate it to a [tpool](https://stackoverflow.com/questions/43947405/how-is-eventlet-tpool-useful) to avoid blocking the event loop.

3- Can you explain the message data flow of inbound and outbound calls of rpc i.e. which objects of nameko are doing what when the message is received.

See [this thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/nameko-dev/dXfzoGGbWk8) on the mailing list

**Comment by rizplate** [comment]
@mattbennett Thanks, your answers and resources are very helpful. I will review them more.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/nameko-service-event-handler-as-a-pull-job-worker/296
