### ISSUE TITLE
logging setup 

### ISSUE THREAD

**Issue by rizplate** [nameko/nameko#527]
How to setup logging for the service and all its dependancies?

**Comment by mattbennett** [comment]
If you use `nameko run` on the command line you can specify [dictConfig](https://docs.python.org/2.7/library/logging.config.html#logging.config.dictConfig) style logging in your configuration file.

See http://nameko.readthedocs.io/en/stable/cli.html?highlight=logging#running-a-service

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/logging-setup/290
