### ISSUE TITLE
lifecycle of service and dependancies

### ISSUE THREAD

**Issue by rizplate** [nameko/nameko#528]
Can someone point me to the documentation where the lifecycle of service and dependancies is shown?
i.e. when is a service created, is its init method called? when are dependencies started, injected and their init methods called

**Comment by mattbennett** [comment]
Please read the [key concepts](http://nameko.readthedocs.io/en/stable/key_concepts.html) page of the documentation. That should answer most of your questions.

Specifically for the questions you've asked here:

> when is a service created, is its init method called?

No. The service class is instantiated every time an entrypoint fires, and that instance is discarded again when the entrypoint returns.

> when are dependencies started, injected and their init methods called

_DependencyProviders_ and all other Extensions are started when the service container is started. _Dependencies_ (the result of `DependencyProvider.get_dependency`) are injected into the instance of the service that is created when an entrypoint fires.

**Comment by rizplate** [comment]
@mattbennett Thanks for the information.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/lifecycle-of-service-and-dependancies/297
