### ISSUE TITLE
Support for init method on service

### ISSUE THREAD

**Issue by rizplate** [nameko/nameko#529]
Can the nameko framework call an init_service method on service, where we can initialize some variables? or do we have to create extensions/dependancies

**Comment by mattbennett** [comment]
Sorry for the slow response to this @rizplate. The answer is that you have to create extensions to do this.

Nameko service classes are instantiated for every worker and discarded afterwards. That means if you save some state to `self.whatever` in one method, it won't be there when the next worker executes. You should use dependency providers to manage state between workers.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/support-for-init-method-on-service/285
