### ISSUE TITLE
Error: No module named C

### ISSUE THREAD

**Issue by MMmaomao** [nameko/nameko#532]
### When I run a test service from a remote windows machine, I got this error.
![image](https://user-images.githubusercontent.com/4596276/38413027-2b003686-39bd-11e8-96c2-0ce39e9b9eed.png)

### test service code
```py
# helloworld.py

from nameko.rpc import rpc

class GreetingService:
    name = "greeting_service"

    @rpc
    def hello(self, name):
        return "Hello, {}!".format(name)
```
I run a rabbitMQ server on a debian machine, and nameko shell command is run properly.
Did i do something wrong?
nameko version 2.8,5
rabbitMQ version 3.7.4

### run nameko shell is ok, and i can see the connection in rabbitMQ panel
![image](https://user-images.githubusercontent.com/4596276/38412874-d56d33ea-39bc-11e8-814b-530e4ef5d196.png)

**Comment by MMmaomao** [comment]
I got it
on windows, you must `cd` to the service py folder.
then `name run service_1`.

**Comment by mattbennett** [comment]
Yep, `nameko run` expects a module path, not a file path.

**Comment by MMmaomao** [comment]
Thanks.
