### ISSUE TITLE
Identifying a memory leak

### ISSUE THREAD

**Issue by raybotha** [nameko/nameko#538]
I'm using the nameko backdoor to try and find the cause of a memory leak, although my service is quite simple and only uses the nameko-sqlalchemy dependency, and rpc.

However the memory use balloons up to around 6GB after handling a few thousand requests, but running pympler does not yield any results:
```
>>> from pympler import muppy
>>> allob = muppy.get_objects()
>>> from pympler import summary
>>> sum = summary.summarize(allob)
>>> summary.print_(sum)
                                          types |   # objects |   total size
=============================================== | =========== | ============
                                    <class 'str |       43963 |      5.76 MB
                                   <class 'dict |        7918 |      3.52 MB
                                   <class 'code |       15101 |      2.08 MB
                                   <class 'type |        2055 |      2.07 MB
                                    <class 'set |        1299 |    502.16 KB
                                  <class 'tuple |        6963 |    472.64 KB
                                   <class 'list |        3412 |    368.48 KB
                                <class 'weakref |        3720 |    290.62 KB
                            <class 'array.array |           2 |    260.79 KB
  <class 'sqlalchemy.sql.visitors.VisitableType |         248 |    256.65 KB
                            function (__init__) |        1145 |    152.07 KB
                            <class 'abc.ABCMeta |         136 |    135.81 KB
                      <class 'getset_descriptor |        1856 |    130.50 KB
                                    <class 'int |        4373 |    122.17 KB
                     <class 'wrapper_descriptor |        1466 |    114.53 KB
```

Is there a part of the nameko service memory that pympler can't access?

**Comment by raybotha** [comment]
Versions:
```
nameko==2.8.4
nameko-sqlalchemy==1.1.0
```

**Comment by mattbennett** [comment]
I have had good success diagnosing leaks with pympler via the backdoor. As far as I'm aware it can see everything.

The problem is probably in nameko-sqlalchemy. Which of the two DependencyProviders are you using? The newer one is more efficient if you're handing a lot of concurrent requests.

**Comment by mattbennett** [comment]
In the two cases I've diagnosed, the causes were:

1. A circular reference causing data in the worker context not to be garbage collected
2. Lots of backed up requests accepted by the @http entrypoint but blocked on the worker pool (not strictly a leak) 

In both cases I could see the objects in pympler though.

**Comment by bludau-peter** [comment]
Hi all, 
I have a similar issue where the RAM usage is about 2GB after 1 long running but finished http request (no other requests made to the service since start) and same results as @raybotha using pympler.  My dependencies are 'pymongo',  'nameko==2.9.0', 'pandas', 'numpy'. Does anyone have any idea why this may happen?

**Comment by raybotha** [comment]
@bludau-peter You should try to use the backdoor with pympler and see if you can spot the issue.

**Comment by mattbennett** [comment]
@bludau-peter my first investigation would be to find out in what situations a process will consume memory and the objects _not_ be visible in pympler. At a guess it's something to do with c-extensions, in your case either in pandas or numpy. The fact that memory grows after only one worker execution suggests it has nothing to do with Nameko or the request-response cycle.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/identifying-a-memory-leak/291
