### ISSUE TITLE
A way to build a URL route

### ISSUE THREAD

**Issue by asyncee** [nameko/nameko#539]
Hello!

I have a service with eight http endpoints and i need to build urls for it with multiple different parameters. Are there any way to implement something like `url_for` in flask:

Example:

```
class Service:
    @http('GET', '/url-one/<token>')
    def handle_url_one(self, request, token):
        pass
    
    @rpc
    def get_url_one(self):
        return '/url-one/' + token   # This is not DRY and error-prone approach
        # Wanted: return self.url_for(self.handle_url_one, token)
```

Thanks!

**Comment by mattbennett** [comment]
Nameko HTTP is built on Werkzeug, which is the WSGI library that underpins Flask. `url_for` is one of the conveniences that Flask adds, so it's not available out of the box.

It's not that hard to implement though. Nameko entrypoints attribute the service methods that they decorate, so you can inspect the service class to find them. This snippet should get you started:

``` python
from nameko.extensions import ENTRYPOINT_EXTENSIONS_ATTR
from nameko.web.handlers import http, HttpRequestHandler
from nameko.rpc import rpc


class Service:
    name = "serv"

    @http('GET', '/url-one/<token>')
    def handle_url_one(self, request, token):
        pass

    @rpc
    def get_url_one(self, token):

        entrypoints = getattr(self.handle_url_one, ENTRYPOINT_EXTENSIONS_ATTR)
        routes = [
            entrypoint.url for entrypoint in entrypoints
            if isinstance(entrypoint, HttpRequestHandler)
        ]
        return routes
```

Returns `['/url-one/<token>']`. The logic you need to substitute the arguments into the string must exist in werkzeug somewhere.

**Comment by asyncee** [comment]
Perfect, thank you! I can use werkzeug's `Rule` to instantiate a url rule, and build url map (werkzeugs `Map`) which can resolve urls with parameters.

The documentation is here: http://werkzeug.pocoo.org/docs/0.14/routing/#werkzeug.routing.MapAdapter.build

Thank!

**Comment by asyncee** [comment]
I have created basic implementation. Check it out: https://gist.github.com/asyncee/afff12559e364b0665c89b0e53341c28

**Comment by mattbennett** [comment]
Nice!

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/a-way-to-build-a-url-route/299
