### ISSUE TITLE
config.yml file for WEB_SERVER_ADDRESS

### ISSUE THREAD

**Issue by gitricko** [nameko/nameko#540]
Is this not possible to do?

```yml
WEB_SERVER_ADDRESS: '0.0.0.0:${PORT:8000}'
```

now i run this command:
```PORT=8080 nameko run --config config.yml trainproxy.service_mocktrainsvr```

hoping webserver address will change to 8080... it does not work.

```Error: Misconfigured bind address `0.0.0.0:${PORT:8000}`. Should be `[address:]port` ```

**Comment by mattbennett** [comment]
It's because you've quoted it.

``` yaml
WEB_SERVER_ADDRESS: 0.0.0.0:${PORT:8000}
```

Will work as you expect.

If you need to quote the value for some reason, you can use the explicit matcher.

``` yaml
WEB_SERVER_ADDRESS: !env_var "0.0.0.0:${PORT:8000}"
```

Also does what you'd expect.

**Comment by gitricko** [comment]
Thanks matt ! It works... should re-read doc carefully !

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/config-yml-file-for-web-server-address/295
