### ISSUE TITLE
Does Nameko implements gRPC?

### ISSUE THREAD

**Issue by t1m0t** [nameko/nameko#544]
Hi,

Simple question : does Nameko implement gRPC? In case not, would it be a good idea to implement it? How hard coded is nameko's RPC? I mean can we implement other RPC library/framework easily?

Thank you

**Comment by mattbennett** [comment]
Looks like you've already figured this out but I will answer here for completeness.

The Nameko @rpc entrypoint uses a custom protocol over AMQP, so it's unrelated to gRPC. However, Nameko is a framework and it is possible to implement any protocol as set of extensions. gRPC is great as a protocol/transport but the development experience is not pleasant. I think the combination of Nameko and gRPC would be really fantastic.

gRPC is essentially protobufs over HTTP2, so it should be possible to implement this in Nameko. I will close this issue and we can use #516 to continue the discussion.
