### ISSUE TITLE
Importing nameko.cli.run to execute run()

### ISSUE THREAD

**Issue by gpkc** [nameko/nameko#549]
Is it ok to use `nameko.cli.run.run()` from my code directly? I want to give nameko some configurations programmatically, using [dynaconf](https://github.com/rochacbruno/dynaconf), but I do not like the idea of copying and pasting (or "adapting") the contents of a run function in my program.
Is `nameko.cli.run.run()` safe to import, or it is not guaranteed to maintain the interface?

**Comment by mattbennett** [comment]
We don't have any kind of formal definition of the "public" APIs, but it should be safe.

The fundamental signature of some `services` to run, and the `config` to use when doing so, is not going to change. In the future it might grow some more keyword arguments like `backdoor_port`, but they'd be backwards compatible.

**Comment by gpkc** [comment]
Do you think it would be appropriate to move some of the functions found under the cli module, such as `run` or `setup_backdoor`, to the utils package for instance? Since they are not really related to the CLI itself, but instead being used by it.

**Comment by mattbennett** [comment]
Yes, probably. I'm not sure `utils` is the right place, but certainly these two things are more about running services than the CLI. Perhaps a new `nameko.run` would be a good module to house them.

**Comment by mattbennett** [comment]
Sorry for the late reply here @gpkc. You're right that things are messy. These facilities have independently evolved and never been refactored into a neater place.

I would welcome a PR that incorporated `run_services` into `nameko.cli.run.run()` and perhaps also moved the whole lot to a better named module like `nameko.run`. 

There is also the `ServiceRunner` class which is really just a convenience wrapper around multiple `ServiceContainers`. I'm not overly keen on it. I don't think it's really necessary and it could certainly be better named (`ServiceContainerCollection` perhaps, although that's a bit long)

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/importing-nameko-cli-run-to-execute-run/292
