### ISSUE TITLE
worker_factory is not mocking dependencies as expected

### ISSUE THREAD

**Issue by muzzi92** [nameko/nameko#555]
Hello,

I'm brand new to Nameko but I have encountered an issue whilst trying to unit test my service. 
I am using pytest, and I was hoping to create a worker so that I can test whether my dependency's function was called inside my service's function. 

However, before getting to that stage, I was doing provisional tests on my newly created worker to check that its dependencies had been mocked with MagicMock. It is at this point it tells me the dependency is not an instance of Mock, and hence I cannot move on to setting side_effects or asserting calls.

Am I missing something that allows worker dependencies to be mocked?

Any tips for testing Nameko are greatly appreciated.

Code below.

Service:
```python
from payment_service import SecondService
from nameko.events import event_handler
from foobar import FooBar

class FirstService(object):

    name = 'first_service'

    dependency = FooBar()

    @event_handler('second_service', 'complete')
    def foo(self, payload):
        self.dependency.bar(param)
```

Test:
```python
from first_service import FirstService
from nameko.testing.services import worker_factory
from unittest.mock import Mock

class TestFirstService(object):

    def test_foo(self):
        service = worker_factory(FirstService)
        assert isinstance(service, FirstService)           #passes
        assert isinstance(service.dependency, Mock)         #fails
```

**Comment by davidszotten** [comment]
nameko always uses the `mock` library (for py2 compat, though i suppose it could be imported conditionally) so you have an instance of `mock.Mock`, not `unittest.mock.Mock`

**Comment by muzzi92** [comment]
Hi David, thanks for the quick reply.

So I removed the unittest mock import first, which resulted in an 'undefined error for Mock'. I then imported `Mock` from `mock` and I get the same error as I did in the first place, which reads something like:

```
assert False
 + where False = isinstance(<foobar.FooBar object at 1234>, Mock)
+ where <foobar.FooBar object at 1234> = <first_service.FirstService object at 5678>.mailer
```

**Comment by mattbennett** [comment]
That error suggests that the mock is not being applied by the `worker_factory`. I can't reproduce though. This works:

``` python
# test_service.py
from nameko.events import event_handler
from nameko.extensions import DependencyProvider
from nameko.testing.services import worker_factory
from mock import Mock


class FooBar(DependencyProvider):
    def get_dependency(self, worker_ctx):
        return "foobar"


class FirstService(object):

    name = 'first_service'

    dependency = FooBar()

    @event_handler('second_service', 'complete')
    def foo(self, payload):
        self.dependency.bar(payload)


class TestFirstService(object):

    def test_foo(self):
        service = worker_factory(FirstService)
        assert isinstance(service, FirstService)           # passes
        assert isinstance(service.dependency, Mock)        # also passes

```
``` shell
$ py.test test_service.py --pdb
============================= test session starts ==============================
platform darwin -- Python 3.5.3 -- py-1.4.34 -- pytest-2.7.3
rootdir: /private/tmp, inifile:
plugins: timeout, stepwise, cov, cagoule, cache, nameko
collected 1 items

test_service.py .
```

**Comment by davidszotten** [comment]
is your `FooBar` definitely a dependency provider? only those get replaced by mocks by the worker factory

**Comment by muzzi92** [comment]
This was really helpful thank you guys, it was a silly mistake on my behalf! I had imported DependencyProvider but forgotten to assign it to the class.

All green now.

Thanks David,
Thank you Matt!

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/worker-factory-is-not-mocking-dependencies-as-expected/287
