### ISSUE TITLE
How to debug nameko with pycharm

### ISSUE THREAD

**Issue by qqqays** [nameko/nameko#560]
I run the nameko RPC service at console with command 'nameko run service_name',
but it can't execute step by step.
Is there method for debugging nameko.

**Comment by mattbennett** [comment]
I don't use PyCharm but I don't see why it would be any different from pdb -- set a breakpoint, and step.

What have you tried and how is it different from what you expected to happen?

**Comment by qqqays** [comment]
thanks

**Comment by willdx** [comment]
Try to do this

```python
import sys
from nameko.cli.main import main

if __name__ == '__main__':
    sys.argv = [
        'run.py',
        'run',
        '--config',
        'config.yaml',
        'users.services.core.service:UsersService'
    ]
    main()
```

![image](https://user-images.githubusercontent.com/5906746/145002983-560598ea-1844-4be1-ae7a-e8b95d9007d8.png)

**Comment by liu3734** [comment]
> Try to do this
> 
> ```python
> import sys
> from nameko.cli.main import main
> 
> if __name__ == '__main__':
>     sys.argv = [
>         'run.py',
>         'run',
>         '--config',
>         'config.yaml',
>         'users.services.core.service:UsersService'
>     ]
>     main()
> ```
> 
> ![image](https://user-images.githubusercontent.com/5906746/145002983-560598ea-1844-4be1-ae7a-e8b95d9007d8.png)

大佬你好，我用你的方式debug启动后出现了异常堆栈
![image](https://user-images.githubusercontent.com/8966977/167099375-128b1241-76be-4d7e-bedb-81fbc0c3a9e7.png)

![image](https://user-images.githubusercontent.com/8966977/167099319-e073e511-c44d-4ce5-8117-3a463041f7a1.png)
并且调用出现了GreenThread的提示
![image](https://user-images.githubusercontent.com/8966977/167099547-771437f0-0349-428a-8c51-244085ce096e.png)
大佬你遇见过吗？怎么解决的呢

**Comment by 0xMerl** [comment]
> > Try to do this
> > ```python
> > import sys
> > from nameko.cli.main import main
> > 
> > if __name__ == '__main__':
> >     sys.argv = [
> >         'run.py',
> >         'run',
> >         '--config',
> >         'config.yaml',
> >         'users.services.core.service:UsersService'
> >     ]
> >     main()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/5906746/145002983-560598ea-1844-4be1-ae7a-e8b95d9007d8.png)
> 
> 大佬你好，我用你的方式debug启动后出现了异常堆栈 ![image](https://user-images.githubusercontent.com/8966977/167099375-128b1241-76be-4d7e-bedb-81fbc0c3a9e7.png)
> 
> ![image](https://user-images.githubusercontent.com/8966977/167099319-e073e511-c44d-4ce5-8117-3a463041f7a1.png) 并且调用出现了GreenThread的提示 ![image](https://user-images.githubusercontent.com/8966977/167099547-771437f0-0349-428a-8c51-244085ce096e.png) 大佬你遇见过吗？怎么解决的呢 @[willdx](https://github.com/willdx)

https://blog.csdn.net/whatday/article/details/105397509
