### ISSUE TITLE
Can I use nameko to transfer some small files?

### ISSUE THREAD

**Issue by MMmaomao** [nameko/nameko#568]
Hi guys,
I just want to upload one small file by using nameko to the server which nameko service is running on.
Is this possible in nameko?
Any advice is very appreciated.
Thank you.

**Comment by kooba** [comment]
Hi @MMmaomao 

https://discourse.nameko.io/ is a great place for any questions about Nameko.

To answer your question, Nameko (just like Flask) is using werkzeug for it's web request processing needs. 

`request` arg you get in your [http entrypoint](https://nameko.readthedocs.io/en/stable/built_in_extensions.html#http) will have [files](http://werkzeug.pocoo.org/docs/0.14/wrappers/#werkzeug.wrappers.BaseRequest.files) attribute on it which "basically behaves like a standard file object you know from Python, with the difference that it also has a `save()` function that can store the file on the filesystem."

**Comment by MMmaomao** [comment]
Hi, @kooba 
Thank you very much
