### ISSUE TITLE
Subprocess in Nameko Service Ignoring `errors = 'replace'`

### ISSUE THREAD

**Issue by nuthanmunaiah** [nameko/nameko#608]
**Describe the bug**

I am using `subprocess.Popen` to create a run a shell command. I expect the output from the command to include non-Unicode characters so I am using `errors = 'replace'` to ignore any Unicode decoding errors and replace the offending characters with � (the prescribed Unicode replacement character). However, the `subprocess` module that is available when I run the code as a nameko service seemed to be ignoring the `errors = 'replace'` argument to `Popen`.

I am certain that the issue described is in the `eventlet` package but I am not directly using `eventlet` so I thought opening an issue here was a good starting point.

**To Reproduce**

I extracted the source code that is essential to demonstrate the issue and created a simple (single file) Nameko service the source code for which is included below. The output from the code when I run it as a Nameko service (using `curl localhost:8000` to invoke the service from a different console) and as a simple Python script is as follows:

```
$ nameko run service
[service] sout - UTF-8 strict
[service] serr - UTF-8 strict
[service] Command Output hello world!!!

^C
$ python service.py
[__main__] sout - UTF-8 replace
[__main__] serr - UTF-8 replace
[__main__] Command Output hello world!!!
```

```
'''service.py'''

import subprocess

from nameko.dependency_providers import Config
from nameko.web.handlers import http


def get_output():
    ostream, estream = run()
    output = ostream.read()
    print('[{}] Command Output {}'.format(__name__, output))
    return output


def run():
    command = 'echo "hello world!!!"'
    process = subprocess.Popen(
        command, shell=True, text=True, errors='replace', bufsize=1,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    sout, serr = process.stdout, process.stderr
    print('[{}] sout - {} {}'.format(__name__, sout.encoding, sout.errors))
    print('[{}] serr - {} {}'.format(__name__, serr.encoding, serr.errors))
    return sout, serr


class NamekoService:
    name = 'nameko'

    config = Config()

    @http('GET', '/')
    def get(self, request):
        return get_output()


if __name__ == '__main__':
    _ = get_output()
```

**Expected behavior**

The `errors = 'replace'` should not have been ignored.

**Environment (please complete the following information):**
 - Nameko version: `nameko==2.11.0`
 - Python version: `Python 3.7.2`
 - OS: `Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64)`

**Additional context**

The command I am using `subprocess.Popen` to run is `git log --patch` and some of the patches will include characters that cannot be decoded to Unicode.

**Comment by mattbennett** [comment]
This is almost certainly a bug in `eventlet.green.subprocess`. Eventlet monkeypatches the standard library `subprocess` module to invoke the green version instead.

You can demonstrate that it's an eventlet bug by reproducing without Nameko, but with the monkey patch applied (by calling `eventlet.monkey_patch()` early in your script).

Unfortunately there is no workaround possible in Nameko; we need the monkeypatch to be applied.

**Comment by nuthanmunaiah** [comment]
Thank you for your response. I will reproduce this issue using `eventlet.green.subprocess` and open an GitHub Issue in the `eventlet` project.
