### ISSUE TITLE
New release of pyyaml 5.1 breaks how config.yml is loaded

### ISSUE THREAD

**Issue by tyler46** [nameko/nameko#611]
hi :) 

I think that new release of pyyaml has introduced some incompatible [changes](https://github.com/yaml/pyyaml/issues/265) that perhaps cause an issue while installing `nameko` package. In particular based on nameko's `setup.py` it's required to install `pyyaml>=3.10`. That results installing latest version of pyyaml which has caused at least to me issues running nameko, because config.yml is not loaded correctly.

**Comment by gitricko** [comment]
yup... saw this today !

**Comment by tyler46** [comment]
thanks @iky !
