### ISSUE TITLE
`--broker` seems exclusive to `--config` in `nameko run`

### ISSUE THREAD

**Issue by vlcinsky** [nameko/nameko#617]
**Describe the bug**
Reading code for `nameko run` it seems, that one can either specify `--config` file or `--broker` url but not both, see https://github.com/nameko/nameko/blob/master/nameko/cli/run.py#L168

**Expected behavior**
When `--broker` value is provided, it shall update possibly loaded config content, not replace it completely.

Note: this issue is based purely on reading the code.

**Comment by vlcinsky** [comment]
Tested on `nameko==3.0.0rc6` I see, that when `--config` is used, value of `--broker` is ignored.

Expected behaviour is that command line options (such as `--broker`) override configuration in config file.

**Comment by iky** [comment]
Hi @vlcinsky, you are right, in Nameko 2.X either config or broker can be specified (broker is ignored if config is specified).

I see that you use the `3.0.0rc6` pre-release. Nameko 3.X [deprecates `--broker`](https://github.com/nameko/nameko/blob/v3.0.0-rc/nameko/cli/commands.py#L89) option (if used a [warning is raised](https://github.com/nameko/nameko/blob/v3.0.0-rc/nameko/cli/main.py#L137)). It is not exclusive to `--config` anymore, but still does NOT override the AMQP URI coming from config file which one would expect. The good news is that you can use new [`--define`](https://github.com/nameko/nameko/blob/v3.0.0-rc/nameko/cli/main.py#L77) option instead. It can be applied on [any config key](https://github.com/nameko/nameko/pull/520#issuecomment-371889499) and it behaves the [expected way overriding config file values](https://github.com/nameko/nameko/blob/v3.0.0-rc/nameko/cli/main.py#L146). This way you can override config file AMQP_URI setting from command line:
```
--define AMQP_URI=pyamqp://guest:guest@localhost
```

**Comment by vlcinsky** [comment]
@iky I really like the configuration related changes - seem well designed.

Anyway, regarding the (now deprecated) `--broker` option - shall we keep it as in 2.x or not?

To me it seems correct to change it so that when `--broker` value is provided, it overrides the AMQP_URI value possibly loaded from a config file, not replacing it completely by it's sole value. This seems to me in line with expected `--define` behaviour.

**Comment by vlcinsky** [comment]
Rewriting CLI to click I have found another place, where `--config` and `--broker` compete.

https://github.com/nameko/nameko/blob/v3.0.0-rc/nameko/cli/main.py#L144 where value of `--broker` is used only, if not defined in config file yet.

This is surprising again, my expectation is, that config bring bigger number of configuration parameters (optionally also AMQP_URI) but if I want to override the AMQP_URI, I use `--broker` to do that unconditionally.

Now I wonder - shall I "fix it" or "preserve backward compatibility" when rewriting CLI to click?

**Comment by iky** [comment]
> Anyway, regarding the (now deprecated) --broker option - shall we keep it as in 2.x or not?

Yep, I'm in favour of keeping it as it was for 2.x. Otherwise we would be deprecating a particular behaviour of a feature which is already deprecated as a whole thing .)

> Rewriting CLI to click I have found another place, where --config and --broker compete.
> 
> https://github.com/nameko/nameko/blob/v3.0.0-rc/nameko/cli/main.py#L144 where value of --broker is used only, if not defined in config file yet.

Yep, I left the deprecated option to be applied the backward compatible way in a sense of when it is used (only if config option not provided) I only changed how it is used so it doesn't replace the whole config by it's sole value anymore.

> Now I wonder - shall I "fix it" or "preserve backward compatibility" when rewriting CLI to click?

I would prefer to keep the old deprecated option behaving the old way even if it is not ideal. At least we are not introducing a potential additional breaking change on something which is going to be soon removed anyway.

**Comment by vlcinsky** [comment]
I completely agree.

The result will be "sort of ideal":
- no breakig change
- for those surprised by `--broker` behaviour, there is advice to use `--define`

From this point of view, this issue is already resolved by WONTFIX to prevent breaking change in deprecated feature.
