### ISSUE TITLE
`nameko backport` probably not working on MS Windows

### ISSUE THREAD

**Issue by vlcinsky** [nameko/nameko#624]
As seen here: https://github.com/nameko/nameko/blob/v3.0.0-rc/nameko/cli/backdoor.py#L11

`nameko` is using `which` command to detect existence of particular executable.

This is very likely to fail on MS Windows as the command with this purpose is named `where` there.

Expected behaviour: Make sure, (possibly fixed) implementation runs on MS Windows too.

**Comment by mattbennett** [comment]
This is superseded by the decision in #625 to remove this command.

Worth noting though that Nameko does not officially support Windows. Anecdotally I gather that quite a few folks run it on Windows, but our CI currently tests on Linux only.

**Comment by vlcinsky** [comment]
Closing as it will be resolved by #625 (removal of `nameko backdoor` subcommand removal).
