### ISSUE TITLE
`nameko backdoor` is too shaky (depends on too many external things)

### ISSUE THREAD

**Issue by vlcinsky** [nameko/nameko#625]
Current implementation of `nameko backdoor` has following issues:
- it depends on existence of either `telnet`, `nc` or `netcat`
- it assumes `rlwrap` command is installed and available
- it assumes existence of command can be tested by `which` command
- if `nc` or `netcat` is used, which has multiple implementation with differing switch for "return CRLF", there are no checks for which implementation is really used

For these reasons the ` backdoor` subcommand is very likely to fail.

# Proposed solutions

## [doc] remove `nameko backdoor` subcommand entirely
Simply describe in documentation, backdoor option exists (with `nameko run`), but to use it, one has to call locally available commands to connect.

## [print] let `nameko backdoor` print instructions only
Allow `nameko backdoor` to specify `--no-rlwrap` and `[host:]port`, but instead of really using it, print clear instructions what shall be called.

It shall state commands, which are assumed as installed (`telnet`, `nc` or `netcat`) plus `rlwrap`.

There shall be listed multiple options of command usages to illustrate how to do that on various OSes (like Linux, BSD, Windows ...).

## [cmdchecks] let `nameko backdoor` do all checks before running real backdoor
This might be quite complex task (e.g. it would have to call `nc --help` to learn, which version of command is installed and search in helpstring for options available).

## [telnetlib] implement `nameko backdoor` using python `telnetlib` from stdlib
This would prevent wide range of checks and problems.

The only remaining issue would be handling existence of `rlwrap`, which is not so difficult.

# Conclusion
I would propose following steps:

- use [doc] initially, it would mean removing `nameko backdoor` subcommand from version 3.x entirely now.
- implement [telnetlib| solution sometime later.

**Comment by mattbennett** [comment]
@vlcinsky thank you very much for this detailed analysis.

I agree with your proposal to remove the `backdoor` command. It is unreliable. Indeed, I always run `rlwrap telnet` for this reason.

I'd suggest one further enhancement to your proposal -- for the `nameko run` command to print the connection instructions when you specified the `--backdoor` option.

**Comment by vlcinsky** [comment]
Resolved by (accepted) PR #620 

Command `nameko backport` removed, `nameko run` informs about how to connect to the backport port.
