### ISSUE TITLE
Is there a way to define service name by config file ?

### ISSUE THREAD

**Issue by xiaojinwhu** [nameko/nameko#638]
Thanks for provide a nice tools for microservice by python.

I find there is a little fuzzy when use docker to scale a service. 
A service make the same work when call it, because the service name is same.
But if need two or more environment ( development, test ...)  on the host, how can I solve it？
thanks

**Comment by kooba** [comment]
Hi @xiaojinwhu the best place to ask questions like this is discussion board here https://discourse.nameko.io/

To answer your question, you have few options:
1. If you really want to share networking between these services and address them by different name  you can use preview release of nameko (`nameko==3.0.0rc6`) with a global config and do something like this: 
```python
# service.py
from nameko import config
from nameko.web.handlers import http


class Foo:
    name = config.get('SERVICE_NAME')

    @http('GET', '/')
    def hello(self, request):
        return 200, f"Hello from {config.get('SERVICE_NAME')}"

```
```yaml
# config.yaml
SERVICE_NAME: ${SERVICE_NAME:foo}
```
and start it by passing service name as environment variable:
```sh
SERVICE_NAME=bar nameko run service --config config.yaml
starting services: bar
```

2. If using docker compose to start your environment, every un of docker compose will create separate network space so your services will not clash

3. If using kubernetes you can create separate namespaces for development and testing to create separate environments.

**Comment by xiaojinwhu** [comment]
> Hi @xiaojinwhu the best place to ask questions like this is discussion board here https://discourse.nameko.io/
> 
> To answer your question, you have few options:
> 
> 1. If you really want to share networking between these services and address them by different name  you can use preview release of nameko (`nameko==3.0.0rc6`) with a global config and do something like this:
> 
> ```python
> # service.py
> from nameko import config
> from nameko.web.handlers import http
> 
> 
> class Foo:
>     name = config.get('SERVICE_NAME')
> 
>     @http('GET', '/')
>     def hello(self, request):
>         return 200, f"Hello from {config.get('SERVICE_NAME')}"
> ```
> 
> ```yaml
> # config.yaml
> SERVICE_NAME: ${SERVICE_NAME:foo}
> ```
> 
> and start it by passing service name as environment variable:
> 
> ```shell
> SERVICE_NAME=bar nameko run service --config config.yaml
> starting services: bar
> ```
> 
> 1. If using docker compose to start your environment, every un of docker compose will create separate network space so your services will not clash
> 2. If using kubernetes you can create separate namespaces for development and testing to create separate environments.

thanks，kooba.  I will try.

**Comment by xiaojinwhu** [comment]
@kooba ,thanks.  I will try later.
