### ISSUE TITLE
TypeError after Upgrading to kombu version 4.6.4

### ISSUE THREAD

**Issue by nuthanmunaiah** [nameko/nameko#655]
**Describe the bug**

Running `nameko run service`, where `service` is the name of the module the code for which is included below, raises a `TypeError: open: path should be string, bytes or os.PathLike, not _NormalAccessor`. Although the bug is similar to #650 and #642, the path to exception is different. See [traceback.txt](https://github.com/nameko/nameko/files/3504167/traceback.txt) for the stack trace.

Note: I am fairly certain that the bug described in this report is in `kombu`. However, I wanted to report it here because I suspect the monkey patching (using `eventlet`) done by `nameko` may be a contributor to the bug rather than the bug being inherently in `kombu`. I also found a trivial workaround that I wanted to include here for others facing the exception under similar circumstances.

**To Reproduce**

Run `nameko run service` with the code for `service` module as shown below.

```
# service.py
from nameko.rpc import rpc

class Service:
    name = 'service'

    @rpc
    def get(self):
        return 'hello world!!!'
```

**Expected behavior**

Running `nameko run service` should have started the service but instead raises in `TypeError: open: path should be string, bytes or os.PathLike, not _NormalAccessor` exception.

```
$ nameko run service
Traceback (most recent call last):
  File "/home/user/scratch/.venv/bin/nameko", line 10, in <module>
    sys.exit(main())
...
  File "/home/user/scratch/.venv/lib/python3.7/site-packages/eventlet/green/os.py", line 107, in open
    fd = __original_open__(file, flags, mode, dir_fd=dir_fd)
TypeError: open: path should be string, bytes or os.PathLike, not _NormalAccessor
```

**Environment**
 - Nameko version:

```
$ pip freeze | grep -P 'nameko|kombu'
kombu==4.6.4
nameko==2.12.0
```
 - Python version:

```
$ python --version
Python 3.7.2
```

 - OS:

```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

**Additional context**

A _workaround_ for this bug is to downgrade the version of `kombu` to `4.6.3` which resolved the issue for me. According to [Changelog](https://github.com/celery/kombu/blob/master/Changelog) from `kombu`, `4.6.4` does not include fixes for any security vulnerabilities so downgrading to `4.6.3` may not pose a problem in the interim.

```
$ pip install kombu==4.6.3
$ pip freeze | grep -P 'nameko|kombu'
kombu==4.6.3
nameko==2.12.0
$ nameko run service
starting services: service
Connected to amqp://guest:**@127.0.0.1:5672//
```

**Comment by aliceh75** [comment]
To confirm, I'm having the same issue:

- Same exception raised;
- Similar stack trace (nameko -> kombu -> importlib_metatadata -> pathlib)
- Downgrading `kombu` from 4.6.4 to 4.6.3 fixes the issue

It looks like it's an eventlet issue, specifically with Pathlib for Python 3.7: https://github.com/eventlet/eventlet/issues/534

Presumably a change in Kombu 4.6.4 means it's now using Pathlib. I don't think the issue is to do with Kombu, and it's not really nameko's fault either. The fix needs to happen in eventlet.

A workaround for nameko would be to allow users not to patch `os`, though I don't know what other repercussions this would have.

**Comment by davidszotten** [comment]
eventlet 0.25.1 is now available with a fix for the pathlib issue

**Comment by nuthanmunaiah** [comment]
Thank you @davidszotten. Updating `eventlet` to `0.25.1` resolves the issue.
