### ISSUE TITLE
Extend documentation with example how to do rpc call

### ISSUE THREAD

**Issue by wieczyk** [nameko/nameko#677]
https://nameko.readthedocs.io/en/stable/

I see only example how to use `nameko shell` to invoke rpc. I think it would be more valuable to give example application, which uses nameko rpc-based service.

**Comment by kooba** [comment]
Hi @wieczyk you can find examples project here https://github.com/nameko/nameko-examples and actual invocation of rpc method here https://github.com/nameko/nameko-examples/blob/master/gateway/gateway/service.py#L31
