### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by vashchukmaksim** [nameko/nameko#679]
Is this project still maintaining and has a future plans or it is better to use other alternatives from now?

**Comment by vashchukmaksim** [comment]
@mattbennett

**Comment by mattbennett** [comment]
Not dead. Plenty of folks out there still using Nameko heavily.

I am temporarily busy with other things but hope to get V3 out of pre-release soon, and add additional maintainers

**Comment by vashchukmaksim** [comment]
Nice to hear that! Thank you!
