### ISSUE TITLE
Importing ABC directly from collections has been deprecated and will be removed in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [nameko/nameko#684]
**Describe the bug**

Importing ABC directly from collections has been deprecated and will be removed in Python 3.8. This issue is similar to https://github.com/nameko/nameko/pull/649

```
nameko/testing/pytest.py
118:    from collections import Iterable
```

**Environment (please complete the following information):**
 - Nameko version: master
 - Python version: 3.8
 - OS: Ubuntu

**Comment by mattbennett** [comment]
This has been addressed in https://github.com/nameko/nameko/pull/726
