### ISSUE TITLE
Service replicas as config param and common logger

### ISSUE THREAD

**Issue by dokazhi** [nameko/nameko#708]
**Please use the [Discourse forum](https://discourse.nameko.io/) for support requests and questions.**

**Is your feature request related to a problem? Please describe.**
When I read the issues with more than 1 worker in container, and doing in same way `nameko run --config config.yaml &` again and again in bash script to describe how many replicas I need... It seems work, buuuuut this way is ugly, anyway logging in this way not working. How did i check it? u ran only 1 service in container and make some request to microservice and get request data in logs, so I ran about 10 workers and make the same request 10 times and my logs was clear.(Max_workers in config I set). Additional information:
Using docker(docker-compose)
nameko version 2.13.0
nameko-grpc 1.0.1

**Describe the solution you'd like**
Some config param for how many replicas do u want to run, and how to check information which worker is down and which is up.
Logging ofc.

**Describe alternatives you've considered**
I am not sure, but may be I will use docker-compose scale parameter and also will use consul, bcause I didn't find solution with service discovery

**Additional context**
docker-compose(part) with nameko
![image](https://user-images.githubusercontent.com/24829504/95566117-f8030980-0a42-11eb-9008-1c36e07f82b9.png)
config.yaml
![image](https://user-images.githubusercontent.com/24829504/95566183-0c470680-0a43-11eb-882e-280c73cf855b.png)

**Comment by mattbennett** [comment]
> Some config param for how many replicas do u want to run, and how to check information which worker is down and which is up.
Logging ofc.

What you're requesting here is outside the scope of Nameko. Running multiple replicas is the domain of whatever environment you're running in -- kubernetes, docker-compose (as you suggested), generic bash wrapper, whatever.
