### ISSUE TITLE
is there any way to call specific rpc service over same channel everytime in nameko

### ISSUE THREAD

**Issue by gunjeetgulatigit** [nameko/nameko#709]
describing my scenario through demo code 
```
from nameko.rpc import rpc, RpcProxy 
class ServiceB:
    name = `service_name`
    serviceA_rpc = RpcProxy(serviceA)

serviceA_resp = self.serviceA_rpc.login(payload)

class serviceA:
    name = service_name

@rpc
    def login(self, request):
     ...
```

here am calling serviceA method from serviceB using RpcProxy

everything is working fine here .
Now when i deployed it over 2 servers using same rabbitMQ for communicating between services so the instance created by server1  may not be accessible to server2 as calls were distributed over channels and some request were handled by server1 and some were handled by server2 .

Is there any thing in rpc call for  broadcast or singleton like in events so to either send request to same server/channel every-time.

**Comment by mattbennett** [comment]
No, RPC intentionally distributes the requests between all available service instances.

If you need a request-response pattern that reaches all available instances, you can probably use the AMQP extensions to construct something yourself.
