### ISSUE TITLE
Why can't I run the nameko command in a shell script

### ISSUE THREAD

**Issue by Fnanshan** [nameko/nameko#712]
When the current side is running, the command 'nameko run --config config.yml module' is very easy to use, but I cannot output the log and Python print information from so library to the file, as if the log has been filtered.
Should I use 'nohup nameko Run --config config.yml module &'?
Can someone help me out.

**Comment by mattbennett** [comment]
I don't understand the question I'm afraid. What are you trying to achieve?

We have a discussion forum at https://discourse.nameko.io that is a better place to ask for help. Please make a post there if you still need help.
