### ISSUE TITLE
AttributeError: 'SubRequest' object has no attribute 'funcargnames'

### ISSUE THREAD

**Issue by antl31** [nameko/nameko#725]
path where exception creates: nameko/testing/pytest.py:274
```
        reorder_fixtures = ('container_factory', 'runner_factory', 'rabbit_config')
        for fixture in reorder_fixtures:
>           if fixture in request.funcargnames:
E           AttributeError: 'SubRequest' object has no attribute 'funcargnames'
```
Python 3.7, pytest==6.2.5

**Comment by mattbennett** [comment]
I can't reproduce this. CI runs fine against pytest 6.2.5 -- https://github.com/nameko/nameko/pull/729

**Comment by vlcinsky** [comment]
@antl31 make sure, you run the test within proper python environment.

I have similar issues, when:
- having pytest installed globally
- having project with virtual environment with it's own pytest
- trying to run the test without having the virtual env being properly activated, thus unintentionally using the global pytest.

I you would have globally installed older version of pytest, I would expect such issues to happen.

**Comment by YarkiMakarki** [comment]
I've solved the same problem by adding addopts = -p no:nameko
