### ISSUE TITLE
Incompatible versions in the resolved dependencies between Nameko and Celery in Kombu

### ISSUE THREAD

**Issue by ouss1919** [nameko/nameko#737]
do you have any plans to increase kombu to 5.0.0 ?

**Comment by robvopb** [comment]
I have same issue.  I'm using nameko in Airflow workflows. Airflow's latest version, requires Celery 5.2.1, which requires: kombu<6.0 and >=5.1.0

**Comment by trolldbois** [comment]
A.k.a, why is Kombu pinned as <5 
The question is kind of similar to dnspython in #744 

Note that I'm myself using/interested in nameko v3-rc10

We see in #564 that the pin occurs in **2018**, when Kombu is bumped from 3.x to 4.x and pinned to "kombu >=4.2.0, <5" to ensure compatibility. 

In **2020**, Kombu released 5.0.0, with the major change being dropping python2 support.
So I assume the version pinning in nameko in 2018 was "conservative" and was done 2 y prior without information about kombu 5 compatibility ?

Note that in 2021, Kombu was released in versions 5.1 and 5.2 with final removal of compat code, support of recent python3 versions, support of recent amqp versions, etc..

So the question is boils down to:
- can Kombu be pinned to ">=4.2.0" only ?

kinda bad news:
- a CI run on py3.9 + kombu latest (5.2) does not seems to provide good results, and hangs in test/test_rpc.py::TestSSL::test_rpc_entrypoint_over_ssl[use client cert-EXTERNAL]

2021-11-30T06:24:32.9535705Z test/test_rpc.py::TestSSL::test_rpc_entrypoint_over_ssl[use client cert-EXTERNAL] FAILED [ 40%]
2021-11-30T06:53:42.0695030Z ##[error]The operation was canceled.

I skipped these tests, and the overall CI comes back with decent results.
So it seems that Kombu 5.2 could be compatible with nameko v3-rc10.
[See https://github.com/trolldbois/nameko/runs/4363856502 for CI details.](https://github.com/trolldbois/nameko/runs/4363856502?check_suite_focus=true)

**Comment by mattbennett** [comment]
Thanks @trolldbois for digging into the git history. I'm not sure why kombu was pinned to <5.

As part of #747 (Python 3.10 support) I have had to remove that pin because there are no 4.x versions of kombu that are compatible. It required a small change to the tests you identified, because Kombu no longer skips SSL cert verification (fixed in https://github.com/celery/kombu/issues/1149), but the test suite is otherwise fine.

**Comment by trolldbois** [comment]
Thanks @mattbennett , great to see you are back !
