### ISSUE TITLE
Why using dnspython 1.x instead of 2.x ?

### ISSUE THREAD

**Issue by waghanza** [nameko/nameko#744]
Hi @mattbennett,

I can see that `dnspython` is required, but on version **1.x**
https://github.com/nameko/nameko/blob/1908be2db9a7ad94de5035dbc5e96917ccc22d60/setup.py#L26

The `dnspython` version **2.x** is available.
https://dnspython.readthedocs.io/en/latest/whatsnew.html#id2

Any specific reason not to use it ?

Regards,

PS : Maybe related to 2.7 usage on CI

**Comment by Jpkwbr** [comment]
Hi,

I think it was due to compatibility issues between Eventlet (used by nameko) and dnspython 2.x.x.
But it seems that Eventlet has fixed those issues now. It may be not relevant anymore to have this limitation.

**Comment by mattbennett** [comment]
Hi @waghanza. @Jpkwbr is correct. There is an issue noting the incompatibility here https://github.com/nameko/nameko/issues/688

Eventlet has fixed this now so we could remove the pin, either conditionally or by dropping support for the older eventlet versions.

**Comment by waghanza** [comment]
> older eventlet versions

Which version are you talking about @mattbennett ?

**Comment by mattbennett** [comment]
@waghanza eventlet is only compatible with dnspython from 0.32.0 onwards. If Nameko wants to drop its pin, we need to stop supporting older eventlet versions.

It seems that dnspython<2 is not supported on Python 3.10 (see #745), so I think that Nameko should update something here.

**Comment by waghanza** [comment]
@mattbennett I don't know if stop supporting eventlet < 0.32 is very used / reliable. As this software is under 1.x, seems reasonable to me to drop support.

As far as I understand, https://github.com/nameko/nameko/issues/745 is more about `dnspython`, and it was solved is 2.x
https://github.com/rthalley/dnspython/blob/3933b49da5239cb9e164b71189bec99a7d243d66/dns/namedict.py#L30

I'm tracking python 3.10 support in https://github.com/the-benchmarker/web-frameworks/pull/4707 somehow

**Comment by mattbennett** [comment]
I have a candidate PR here that adds support for Python 3.10 https://github.com/nameko/nameko/pull/747

Eventlet 0.33.0 is the only version that supports Python 3.10, and it is very new. My PR maintains the pin of dnspython<2 for Pythons < 3.10 because I'm not ready to drop support for the older versions of eventlet.

**Comment by waghanza** [comment]
I'll be glad to update the use it then in https://github.com/the-benchmarker/web-frameworks/pull/4707

**Comment by mattbennett** [comment]
https://github.com/nameko/nameko/pull/747 has been merged now.
