### ISSUE TITLE
Timer work on master process or every process?

### ISSUE THREAD

**Issue by caichudong** [nameko/nameko#759]
I test the code timer just run once, how should i  be sure the timer run on master process？

`
from nameko.timer import timer
my_cache = 0.0

class Service:
    name ="service"
    @timer(interval=2)
    def add(self):
        global my_cache
        mycache = mycache+1
        print(mycache)
`

**Comment by aryatalathi** [comment]
Can I work on this issue? Waiting for a reply. Thank you.

**Comment by mattbennett** [comment]
It's unclear what you mean by "master process".

The `add` method on the service you've written will execute every two seconds while the service is running. As with all entrypoints, each execution will happen in its own worker thread.

I'll close this issue. If you still have questions, [the forum](https://discourse.nameko.io) is a better place to ask them.
