### ISSUE TITLE
nameko multiprocess problem

### ISSUE THREAD

**Issue by louiswang132** [nameko/nameko#763]
**Describe the bug**
When using ProcessPoolExecutor, the nameko process reports an error, 2022-08-17 22:16:41,600 /Users/apple/Desktop/project/ops-dolphin/venv/lib/python3.6/site-packages/kombu/mixins.py[ line:180] - WARNING [None None] Connection to broker lost, trying to re-establish connection..., no error will be reported when using ThreadPoolExecutor, but during use, it is found that ThreadPoolExecutor can only use one CPU core during multitasking concurrent processing , the concurrency efficiency cannot be improved, and when one core cpu is full, the nameko main process receives the http request response slowly.

**To Reproduce**
    with ProcessPoolExecutor(3) as executor:
        for project in range(3):
            fs.append(executor.submit(test))

**Expected behavior**

**Environment (please complete the following information):**
 - Nameko version: 2.12.0
 - Python version:3.6
 - OS: mac

**Additional context**
Can rpc requests use multi-core processing requests like uwsgi, and whether they can use ProcessPoolExecutor to process tasks concurrently

**Comment by mattbennett** [comment]
Nameko uses eventlet for concurrency, which does not interoperate with multiprocessing.

If you want to fan-out into many concurrent processes, you can accomplish it with Nameko's own primitives. For example, you could dispatch multiple events using the `EventDispatcher` dependency provider, and then handle those (in the same service, or a different one) with the `@event_handler` entrypoint.
