### ISSUE TITLE
Do you die? we need you to improve Nameko Library

### ISSUE THREAD

**Issue by phuclb1** [nameko/nameko#765]
Do you die? we need you to improve Nameko Library

**Comment by krzysiekfonal** [comment]
I agree, great potential it has but seems like author doesn;t have a time for it :(

I'm using it in work now intensively, so I gonna start improving it myself. If anyone is interested in help or use my fixes/improvements I welcome to this repo:
https://github.com/krzysiekfonal/nameko.

Those are points I gonna improve/fix first:
- switch master to 3.0 version
- allow debugging
- fix standalone clients
- timeouts
- use Kombu instead rabbitmq directly to make it independent
- better events support (receiver doesn’t have to know the source)
- newer dependencies

**Comment by joaomcarlos** [comment]
@krzysiekfonal Are you still working on it? On GitHub I dont see any progress from you, developing it internally?

**Comment by PabloEmidio** [comment]
Looks like @mattbennett came back to accept a PR. I really hope nameko receives the due attention.

**Comment by mattbennett** [comment]
Hello, yes I am back. A change of circumstance means I have more time available for Nameko now.

My immediate priority is release 3.0 as a stable version, including updated docs on how to actually use 3.0. I'll get that done first, and then we can start conversations about the next most important things to improve.

**Comment by joaomcarlos** [comment]
@mattbennett Hows it going?
