### ISSUE TITLE
Linking nameko and golang by RPC

### ISSUE THREAD

**Issue by RasoulRostami** [nameko/nameko#772]
I have developed a microservice project with Nameko. I have a nameko gateway and two other microservices that call each other with RPC. Now I need a new microservice based on Go. I can't find any library or example to implement RPC request/response between nameko and Go services.  Could you help me solve this problem?

**Comment by mattbennett** [comment]
I'm not aware of any go clients that are compatible with Nameko's AMQP-based RPC implementation.

For RPC calls between services in different languages, gRPC is a common choice. If you added gRPC endpoints to your services using [nameko-grpc](https://github.com/nameko/nameko-grpc (or convert your existing endpoints) there are many gRPC clients available that you could use to call them.
